### ISSUE TITLE
Autotrack Logo?

### ISSUE THREAD

**Issue by watzak** [googleanalytics/autotrack#100]
Do u actually have a autotrack logo?

![autotrack2](https://cloud.githubusercontent.com/assets/8505970/18316998/e4ac43de-751c-11e6-8407-ad2f16e8bc39.png)

![autotrack3](https://cloud.githubusercontent.com/assets/8505970/18317014/f36fecfe-751c-11e6-9368-688de7ceb33f.png)

![autotrack_logo3](https://cloud.githubusercontent.com/assets/8505970/18317020/f81dcc94-751c-11e6-982c-084a75d7cfae.png)

**Comment by philipwalton** [comment]
Thanks, but I don't think this project needs a logo. And if we decide to add one in the future, we'll probably have one of the designers on our team do it.
