### ISSUE TITLE
Enhancement Request: Dynamically add elements to track

### ISSUE THREAD

**Issue by k-mada** [googleanalytics/autotrack#102]
It would be nice to be able to add elements you want to track (i.e ImpressionTracker) dynamically. It looks like currently that you have to declare the elements you want to track right when you require the plugin. There are scenarios where we need to dynamically create element IDs and then have them tracked.

**Comment by philipwalton** [comment]
Thanks for the suggestion. I agree this is probably a feature worth adding.

You can work around this for the moment by [removing](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/impression-tracker.md#methods) the plugin and then and re-requiring it whenever the set of elements you want to observe changes. It's not a great solution, but it should work.

**Comment by k-mada** [comment]
Thanks, I will try that out for now.

**Comment by philipwalton** [comment]
Fixed via #111.

**Comment by k-mada** [comment]
Thank you for doing this! I will check it out.
