### ISSUE TITLE
url change track as page view

### ISSUE THREAD

**Issue by Pau1fitz** [googleanalytics/autotrack#103]
@philipwalton Hi Philip,

I was hoping to use this library, but unfortunately I am using GTM, so have had to find an alternative. I found this [blog post](https://www.clickinsight.ca/about/blog/how-to-autotrack-gtm#url-change) and have implemented number 6. URL Change Tracking. 

When I check the debug preview it seems to all be working and the new tag is firing each time the url changes, however, when I look at the live analytics dashboard, this is not being marked as a Page View each time the url changes. Do you have any idea if the dashboard should show these as Page Views changing live?

It's an angular app by the way, if that makes any difference.

**Comment by philipwalton** [comment]
The Real Time view should show pageviews, so your implementation may be incorrect.

Regardless, I wouldn't use the Real Time view for debugging, this guide shows several better options:
https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging
