### ISSUE TITLE
Requiring the `autotrack` plugin no longer requires all sub-plugins be default

### ISSUE THREAD

**Issue by jp26jp** [googleanalytics/autotrack#104]
1. What does this mean?
2. Can't find any documentation on what this means.
3. The reference URL goes to the changelog which isn't helpful.

These aren't complaints, just observations 😄

**Comment by philipwalton** [comment]
That URL should probably point here instead, since its directly related to upgrading from a pre-1.0 version to 1.0:
https://github.com/googleanalytics/autotrack/blob/master/docs/upgrading.md

**Comment by jp26jp** [comment]
That link is definitely more helpful. 

The wording of the error is a little confusing. I'm new to autotrack, so I read the error as:

> [...] **sub-plugins** *do not* need to be included.

Now that (I think) I understand the error a little better, this might be slightly better wording:

> Requiring the `autotrack` plugin does not require sub-plugins to be set to default

**Comment by philipwalton** [comment]
I've updated the language (via https://github.com/googleanalytics/autotrack/commit/ca61e5a57fb72db066cb12c8a27fc0d9a99811f7) and cut a new version. Hopefully it's clearer now.
