### ISSUE TITLE
Beacon Transport always says "cancelled" and no event is sent to GA on Chrome

### ISSUE THREAD

**Issue by chibicode** [googleanalytics/autotrack#108]
I can't get `outboundLinkTracker` or `eventTracker` to work on Chrome v53 - I tried to use `analytics_debug.js`, and the params all look correct:

![image](https://cloud.githubusercontent.com/assets/992008/19338178/10056956-90d0-11e6-8135-a0189e8e1a5c.png)

However, the beacon request always says cancelled on Chrome, and the data is not sent to Google Analytics.

![image](https://cloud.githubusercontent.com/assets/992008/19338193/225ce71e-90d0-11e6-9a4e-386b67b80967.png)

Tracking works fine on Safari (no beacon support), and even on Chrome, if I switch `transport` to `image` and set links to use `_target="blank"` they work fine.

I don't even know how to debug these cancelled beacon requests. Any ideas?

**Comment by philipwalton** [comment]
I can't reproduce this issue on Chrome 53 on Mac. Is it possible you're using a browser extension that's cancelling the requests?

Either way, the beacon transport mechanism is a feature of analytics.js that's not specific to autotrack, so if you continue to have issues with it, can you please report it to the Google Analytics developer issue tracker here:
https://code.google.com/p/analytics-issues/issues/entry
