### ISSUE TITLE
Declarative tracking of internal forms

### ISSUE THREAD

**Issue by jantichy** [googleanalytics/autotrack#11]
`<form action="/subscribe.php" data-form-category="Forms" data-form-action="Submit" data-form-label="Newsletter Subscribe">`

Anyone? :)

**Comment by philipwalton** [comment]
Yeah, I think this is a good idea, and partially aligns with something else I was thinking about but wasn't sure the best API to expose it.

Basically I think it should be possible to declaratively send any event (arguably not just events but any hit type). Autotrack just needs to know what to listen to and then it needs to know what fields to look for on the element itself.

Listening to form submits would have a pretty negligible impact, but something like listening to scroll events or mouse move events would probably not be a good idea, so we'd have to be careful with what we turned on by default.

**Comment by mattpolicastro** [comment]
Taking a look around, and would make sense to tweak OutboundFormTracker to cover this case? I'd be happy to play around with it.

**Comment by philipwalton** [comment]
This is now supported in version 1.0.
