### ISSUE TITLE
What about adding it to a CDN ? like jsdeliver ?

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [googleanalytics/autotrack#110]
What about adding files required to run that project live to a CDN and thus ease activation and deployment ??

Anything preventing that ?

https://github.com/jsdelivr/jsdelivr

**Comment by philipwalton** [comment]
We have no plans to host this on a CDN, as users should ideally only be serving the plugins they're actually using. Hosting on a CDN would encourage the practice of not doing that.

**Comment by philipwalton** [comment]
FWIW, there are a number of CDNs that automatically serve files hosted on npm. unpkg.com is an example, and you can get the latest autotrack.js file from: https://unpkg.com/autotrack/autotrack.js

**Note:** This is good for development or testing, but I wouldn't recommend using this service in production.

**Comment by googleanalyticsresoneo** [comment]
Hi,
I don't see what is wrong in using a CDN in production, it's the purpose of a CDN.
I don't see either why self hosting is better.
When you only have access to Google Tag Manager for example, you need the scripts to be hosted somewhere.

Loading https://cdn.rawgit.com/googleanalytics/autotrack/1.0.3/autotrack.js seems to work fine (cache expires in 10 years !)
But loading https://cdn.rawgit.com/googleanalytics/autotrack/1.0.3/lib/plugins/event-tracker.js breaks with "require" being undefined, why ?

Why not adding this to the setup documentation ?

**Comment by cruzanmo** [comment]
@googleanalyticsresoneo, this might be relevant: https://blog.chibicode.com/you-can-submit-a-pull-request-to-inject-arbitrary-js-code-into-donald-trumps-site-here-s-how-782aa6a17a56

**Comment by googleanalyticsresoneo** [comment]
Loading a given version, not a branch, would prevent from that risk since it is frozen

**Comment by philipwalton** [comment]
> I don't see what is wrong in using a CDN in production, it's the purpose of a CDN.

I said I wouldn't recommend using unpkg.com in production, not any CDN. unpkg.com makes no uptime guarantees.

> I don't see either why self hosting is better.

If any of the autotrack plugins fail to load, no tracking will happen for that particular visit. Hosting the autotrack code on a domain that's not the same as the rest of your code increases the risk of that happening.

> When you only have access to Google Tag Manager for example, you need the scripts to be hosted somewhere.

Autotrack is intended for developers implementing their own tracking in code. If you're using GTM you can do much of what autotrack does through GTM tag configuration options, and that is the recommended practice for GTM users.
