### ISSUE TITLE
Adding new elements for Impression Tracking

### ISSUE THREAD

**Issue by cemo** [googleanalytics/autotrack#118]
Programmatically one can add elements to track impression. Please support adding new elements programmatically for impression tracking. 

Use case: In some of our applications we are using pagination by ajax. I mean that when a user reaches the end of page, new elements are fetched into the page. For these cases, actually for all ajax cases, it would be nice to add some new elements for tracking.

**Comment by philipwalton** [comment]
This is currently supported. It was [added in version 1.1.0](https://github.com/googleanalytics/autotrack/blob/master/CHANGELOG.md#110-2016-10-18) via https://github.com/googleanalytics/autotrack/pull/111.

**Comment by cemo** [comment]
@philipwalton What is the behaviour of calling multiple times for different elements? 

```
startObservingBtn.addEventListener('click', function() {
  ga('impressionTracker:observeElements', ['foo']);
});

startObservingBtn.addEventListener('click', function() {
  ga('impressionTracker:observeElements', ['bar']);
});
```

What I would like to do is that tracking `foo, bar`. I can programmatically remove all elements and add again but this time I will miss if `foo` has been seen before. This case is happening in ajax based pages. A content added later by ajax must be added in observe elements.

Hope this makes it clear.

**Comment by philipwalton** [comment]
> What is the behaviour of calling multiple times for different elements?

There's no problem with calling it multiple times with different elements. The following two code blocks do the exact same thing:

```js
ga('impressionTracker:observeElements', ['foo']);
ga('impressionTracker:observeElements', ['bar']);
```

```js
ga('impressionTracker:observeElements', ['foo', 'bar']);
```

> What I would like to do is that tracking foo, bar. I can not do initially because bar is loaded async by user interactions in a later phase.

`impressionTracker` supports observing an element before it's added to the DOM. Did you try it? *(It's probably worth making that more clear in the documentation.)*

> Hope this makes it clear.

I think it's clear. At this point I'd just suggest trying it and seeing if it works.

You can look at the network tab in your devtools to see what hits are being sent. If something is not working as expected after you've tried implementing it, let me know (with code examples), and I can fix it if there's a bug, but I'm pretty sure everything you've described is currently possible.

**Comment by cemo** [comment]
Thank you, I will try and let you know about result.
