### ISSUE TITLE
A mistake in outboundLinkTracker documentation

### ISSUE THREAD

**Issue by gamtiq** [googleanalytics/autotrack#120]
It seems there is the following mistake in [outboundLinkTracker documentation](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/outbound-link-tracker.md#default-field-values):
> Note: the reference to **form** in the table above refers to the **&lt;form>** element being clicked.

I suppose `link` should be used instead of `form`.

**Comment by philipwalton** [comment]
Thanks! This has been fixed.
