### ISSUE TITLE
event tracking broken for web components

### ISSUE THREAD

**Issue by OrenBochman** [googleanalytics/autotrack#121]
Using autortracking of events fails with (Polymer) web components  (under chrome).

I tested and found the event bubble up the DOM but the source & target of the event change as it bubles so that when the event is captured by autotracking it no longer has the ga-* attributes in the correct context. 
e.g.
`<body>`
  `<my-app>`
    `<my-button ga-on="click" ga-event-category="cat" ga-event-action="click">`
       Play Video
     `</my-button>`
  `</my-app>`
`</body>`

in this case the event will bubble up to body and have my-app as source and target

**Comment by philipwalton** [comment]
I can't reproduce this. Here's what I tried:

1. I create a new polymer projects using [these starter kit instructions](https://www.polymer-project.org/1.0/start/toolbox/set-up)
2. I added a [`<paper-button>`](https://elements.polymer-project.org/elements/paper-button) instance to one of the views
3. I added the `ga-on="click"`, `ga-event-category="cat"`, and `ga-event-action="click"` attributes just as you've described.

When I run the app and click on the paper button, the event category and action values are set to `"cat"` and `"click"` respectively.

If this isn't what you're seeing can you please post how to reproduce your setup, or better yet post a demo that I can look at?

**Comment by philipwalton** [comment]
I'm closing this as I haven't heard back. Feel free to reopen if you can show me how to reproduce what you're seeing.
