### ISSUE TITLE
Using rootMargin breaks the plugin 

### ISSUE THREAD

**Issue by thomaslein** [googleanalytics/autotrack#124]
Having  rootMargin: '-20px 0' in options is breaking the plugin with following error:
**analytics_debug.js:10 : Error creating a plugin instance**

**Comment by philipwalton** [comment]
Ahh, this is a problem with the documentation that needs fixing and clarification.

`IntersectionObserver` instances only accept a `rootMargin` option in pixel or percentage values. In other words, `'-20px 0'` is invalid, but `'-20px 0px'` works.

I'll update the documentation to clarify.

**Comment by philipwalton** [comment]
Fixed via 0238cfe34f96b7b87261645550eb295c161d012c.
