### ISSUE TITLE
event tracking not working as expected

### ISSUE THREAD

**Issue by tyrw** [googleanalytics/autotrack#125]
I'm following the example from the docs and no events get sent.  E.g.:

    require('autotrack')
    require('autotrack/lib/plugins/clean-url-tracker')
    require('autotrack/lib/plugins/outbound-link-tracker')
    require('autotrack/lib/plugins/url-change-tracker')
    ga('create', 'UA-MYCODE-1', 'auto')
    ga('require', 'cleanUrlTracker')
    ga('require', 'outboundLinkTracker')
    ga('require', 'urlChangeTracker')

    // Nothing sent
    ga('send', 'pageview')

However if I just import analytics.js, it works fine:

    require('./analytics.js')  // downloaded from https://www.google-analytics.com/analytics.js
    ga('create', 'UA-MYCODE-1', 'auto')

    // Sends fine
    ga('send', 'pageview')

Am I configuring autotrack correctly, or is there a bug?

**Comment by tyrw** [comment]
If it is helpful, logging `ga` just before `ga('send', 'pageview')` in the first (non-working) case gives

    function () {
        (window[gaAlias]['q'] = window[gaAlias]['q'] || []).push(arguments);
    }

while logging it in the second (working) case gives

    function N(a) {
        J(1);Z.D.apply(Z, [arguments]);
    }

**Comment by philipwalton** [comment]
This code is suspicious:

```js
require('autotrack')
require('autotrack/lib/plugins/clean-url-tracker')
require('autotrack/lib/plugins/outbound-link-tracker')
require('autotrack/lib/plugins/url-change-tracker')
```

Requiring just `autotrack` will require all sub-plugins, so you don't need to require it as well as individual plugins. In fact, if you only want to require individual plugins, requiring just `autotrack` will actually cause you to import everything.

I suspect the problem is you're not compiling the code through a build step. The `require` statement is actually a node.js idiom, so if you're running it natively in the browser you're probably getting an error.

Can you check your developer console to make sure you're not getting errors?

Better yet, load the [debug version of analytics.js](https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging) and see what it says. That will help you figure out the root of your problem.

**Comment by tyrw** [comment]
Fair point about the suspicious code.  I have tried both ways (autotrack only, and plugins only) with no success, so this was a kitchen sink approach.

I think you are correct about the code not being put through a build step.  There are no errors in the dev console, and I'm not sure what you mean by load the debug version of analytics.js.  The regular version of analytics.js works fine, so it seems like it is something to do with autotrack or how I'm building it.  If I am misinterpreting and there is a way to get debug version in autotrack then I am all for trying that.

This is in a file being processed by webpack.  It uses e.g.

    import Vue from 'vue'
    import Signup from '../templates/signup.vue'
    import 'autotrack'  // or require('autotrack'), same result

Is there a pre-built file I can `import` instead of the one referenced by `autotrack` in npm?

**Comment by philipwalton** [comment]
> I'm not sure what you mean by load the debug version of analytics.js

The link in my comment shows how to load the debug version of analytics.js, it also explains what it does and how it's useful.

> Is there a pre-built file I can import instead of the one referenced by autotrack in npm?

If you're using Webpack, then importing the way you've shown is definitely the way to go. Here's a file from the [Google Analytics Demos & Tools site](https://ga-dev-tools.appspot.com/) that also uses Webpack and also imports autotrack via `import` statements like you've shown.

https://github.com/googleanalytics/ga-dev-tools/blob/901fb2415a60d1a789540b23fc0bcf6615e21331/src/javascript/analytics.js#L16-L21

Again, I suspect that if you load the debug version of analytics.js, you'll see some warnings or logs printed to the console that'll tell you what's wrong. I suggest doing that.

**Comment by tyrw** [comment]
I just implemented using `import 'analytics_debug.js'` and it works same as the `analytics.js` script: all page changes are registered and work as expected.  No errors in the console, just lots of informational messages like

    Executing Google Analytics commands.
      Running command: ga("send", {hitType: "pageview", page: "/auth/signup", location: "http://localhost:3000/auth/signup", title: "signup"})
      ...

Let me know if there is something in particular I should be looking for here -- everything looks to be in order.

When I try importing all of the autotrack pieces independently:

    import 'autotrack/lib/plugins/clean-url-tracker';
    import 'autotrack/lib/plugins/event-tracker';
    import 'autotrack/lib/plugins/impression-tracker';
    import 'autotrack/lib/plugins/media-query-tracker';
    import 'autotrack/lib/plugins/outbound-link-tracker';
    import 'autotrack/lib/plugins/page-visibility-tracker';

I get the same result as before -- no events are sent.  Is it possible that this has something to do with webpack config?  Other packages are working fine, but not sure if there is a difference in how they need to be processed.

**Comment by philipwalton** [comment]
Do you see any lines in the console that say something like "Waiting on ______ plugin..."?

Without knowing more about your setup or seeing your code, it's hard to say what could be going wrong. Do you have the page publicly available anywhere?

**Comment by philipwalton** [comment]
As an aside, I wouldn't recommend loading analytics.js (or the debug version) via webpack. I'd keep it as a separate script tag and load it async as [recommended by the docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet):

```html
<!-- Google Analytics -->
<script>window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
```

When you load it via webpack you're including it in your main bundle, which means visitors to your site won't be able to take advantage if it being in their browser cache from a previous visit or from another site using Google Analytics.

**Comment by tyrw** [comment]
The console is completely clean unless I choose to log something -- no errors or messages.  I don't have a non-working version up to look at, so will try to reproduce it somewhere you can check it out.

Thanks for the tip on cached version of GA also!

**Comment by tyrw** [comment]
@philipwalton here is a clean example that works with `analytics.js` but not with `autotrack`

https://github.com/tyrw/autotrack-example

**Comment by philipwalton** [comment]
Ahh, the problem is you have to have *both* analytics.js and autotrack. I created a quick PR to show you how to get it working: https://github.com/tyrw/autotrack-example/pull/1

**Comment by tyrw** [comment]
Thanks!  I think I misunderstood the purpose of this library as a replacement for `analytics.js` that works with SPAs.  We can create events within our hooks, so we probably don't even need autotrack 😃 

Thanks for the back and forth!

**Comment by philipwalton** [comment]
You can track events manually within your hooks if you want to, but there are [a fair amount of gotchas](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications) when tracking SPAs that autotrack automatically handles for you.

Also, if you want to track outbound link clicks there are also [a lot of gotchas](https://developers.google.com/analytics/devguides/collection/analyticsjs/events#outbound_link_and_form_tracking) that have to do with certain browsers not executing JavaScript code after a link is clicked and the page starts unloading.

If you don't use autotrack, you should at least have a look at [the plugin implementations](https://github.com/googleanalytics/autotrack/blob/master/lib/plugins/outbound-link-tracker.js) to make sure you're handling these cases correctly, or the data you're collecting may be incomplete.

**Comment by tyrw** [comment]
Thanks for the additional color, and I can virtually guarantee you we are failing all of those gotchas, so autotrack makes more sense in light of this explanation.

Overall feedback then would be to make 2 things clearer in the readme:

1. autotrack works as an addition to analytics.js
2. autotrack helps you avoid all kinds of gotchas

In reading the current readme, my take was that the package was a smaller version of analytics.js that I could make even smaller by only including the parts that I wanted.

The value to us by far is to avoid the gotchas, since we can achieve basic tracking with a one-liner in an afterHook.  I imagine this might be the case for a lot of others too, but worth testing.

Thanks again.
