### ISSUE TITLE
npm out of date

### ISSUE THREAD

**Issue by BradDenver** [googleanalytics/autotrack#128]
Howdy. Thanks for making these plugins available.

npm still has 1.0.3 so could you please publish the 1.1.0 update to npm.

Took me a while to figure out why `impressionTracker:observeElements` wouldnt work for me 😛

**Comment by philipwalton** [comment]
Published 1.1.0. Sorry about that!

**Comment by BradDenver** [comment]
Pefect thanks. I know I have missed that step before with my own repos.
