### ISSUE TITLE
hitFilter for clean-url-tracker?

### ISSUE THREAD

**Issue by pbowyer** [googleanalytics/autotrack#130]
It would be fantastic if a custom filter could be passed to the `clean-url-tracker`, so that if specific URLs need extra processing I don't have to write another plugin/modify & build a custom version of this one.

Other plugins are able to take `hitFilter`, and I'm not clear if there's a technical limitation that prevents this one from doing so.

**Comment by philipwalton** [comment]
Thanks, this was discussed in #96, but main reason `cleanUrlTracker` doesn't have a `hitFilter` option is it doesn't send hits, but I agree that a more generic way to modify all URLs would be nice, and it's planned for an upcoming release.
