### ISSUE TITLE
Possible to add single prefix to all pages?

### ISSUE THREAD

**Issue by winehook** [googleanalytics/autotrack#134]
Hello -- first of all, thanks very much for this tool, it really fit the bill for a project we launched a few months back.

One thing I'm wondering, though: right now we're running this on an SPA that has its own property in Google Analytics.  Ideally, since this SPA is a small part of our larger main website, we'd like it to use that website property instead.  

The problem is, if I just change the Google Analytics property number, we'll have overlapping pages in the GA reporting.  In other words, we won't be able to tell the / in this SPA from / on our main website, or the /search page in this SPA from the /search page in our main website.  Our editorial folks don't want that to happen (even though they could use Page Titles to tell the difference).

If there was a simple way I could add a single prefix to every page in this SPA (such as /SPA), that would be a magical fix.  Then I could have it send /SPA/ and /SPA/search, and there'd be no overlapping.  

Is that possible, somehow?  I know that there's a ga('send','pageview') command that fires this off, but I'm not sure how I'd go about adding a prefix to every value sent.  My SPA (Backbone-powered) dynamically changes the URL all the time.  

Any nudge you can provide in the right direction would be much appreciated.

**Comment by philipwalton** [comment]
To answer your specific question, with the new [`urlFieldsFilter`](https://github.com/googleanalytics/autotrack/blob/2.0.0-rc.2/docs/plugins/clean-url-tracker.md#options) option that will be available in [version 2.0](https://github.com/googleanalytics/autotrack/pull/127), you'll be able to arbitrarily define a function to rewrite all URLs. That might solve your problem.

More generally though, have you considered using a separate property to track the SPA, then that data wouldn't appear in your reports. Alternatively you could use view filters to create views that contain both the separated data as well as the combined data.

**Comment by winehook** [comment]
Wow, thanks for writing back so fast.  

Ah, that's good to know -- thanks very much.  (I guess I wasn't clear earlier -- we do have this data going into a separate property right now, it's just that our editorial team hates having to look in two different places for reports.  Spoiled, I guess, right? :) 

One thing I'm experimenting with now is this:

`        <script>
        window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
        ga('create', 'XXXXXXXXX', 'auto');
        ga('require', 'autotrack');
        ga('require', 'eventTracker');
        ga('send', 'pageview', {
            page: '/SPA'+location.pathname
        });
        </script>`

In my early testing that appears to be working -- but I may be missing some subtle ways in which it won't?  If that's no good, perhaps I'll just wait for 2.0?

Dave

**Comment by philipwalton** [comment]
Two things:

1) You don't need to run `require('autotrack')` anymore, actually it doesn't do anything. See the [1.0 upgrade guide](https://github.com/googleanalytics/autotrack/blob/1.1.0/docs/upgrading.md#global-changes) for details.

2) Your pageview code below will work for the initial pageview, but it won't work for subsequent SPA pageviews:

```js
// ...
ga('send', 'pageview', {
  page: '/SPA'+location.pathname
});
```

You can actually use the new version today via the release candidate [2.0.0-rc.2](https://github.com/googleanalytics/autotrack/tree/2.0.0-rc.2) (also available on [npm](https://www.npmjs.com/package/autotrack)).

**Comment by winehook** [comment]
You know, I wondered about that -- but weirdly, it does appear to be working.  When I click around on the SPA, I'm seeing pageviews each click, even though they are all powered by Bootstrap.

Perhaps since my app actually rewrites the URL (in order to allow for bookmarking), it's reloading enough to fire off the new pageview each time? 

Still, it seems like using the 2.0 version is the best fix -- I'll take advantage of that.  Is it ready for production usage?

**Comment by philipwalton** [comment]
Unless you've included the [`urlChangeTracker`](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/url-change-tracker.md) plugin, analytics.js is not automatically tracking SPA pageviews for you. If you're seeing pageviews then you've either implemented code to do that yourself, or you're using another library that does it (or your SPA isn't actually working and you're simply seeing real pageloads).

Note that even if you *are* seeing pageviews, you won't be seeing pageviews with the `/SPA` prefix based on the code you've shown above.

> Still, it seems like using the 2.0 version is the best fix -- I'll take advantage of that. Is it ready for production usage?

I'm using it in production. I haven't seen any issues, and I haven't heard of any issues from folks using the beta. I'll probably release 2.0 next week.

**Comment by philipwalton** [comment]
Version 2.0 has been released, so I'm going to close this. Feel free to let me know if the new version doesn't suit your needs.
