### ISSUE TITLE
Impression tracking not working on mobile?

### ISSUE THREAD

**Issue by lauriinc** [googleanalytics/autotrack#136]
I noticed that element impressions are not tracking on mobile. I tried google analytics debug version on safari inspector and noticed that no impression events are triggered.

should it work or is impression tracking available only for desktop?

**Comment by lauriinc** [comment]
Ah too bad I missed that for to work outside chrome you need also IntersectionObserver polyfill.

Shame that we missed a lot of useful analytics data before this. Any hope to get this built in into autotrack in the future and load it only for unsupported browsers?

**Comment by philipwalton** [comment]
The polyfill is relatively expensive to run, so I wouldn't want to force it on everyone using this plugin. In my opinion, having it optional gives the best of both worlds.
