### ISSUE TITLE
localStorage access

### ISSUE THREAD

**Issue by tinovyatkin** [googleanalytics/autotrack#140]
Seems that you forgot `try / catch` wrap `localStorage` access somewhere
![screen shot 2017-02-21 at 20 00 01 pm](https://cloud.githubusercontent.com/assets/5350898/23190813/8c9cde92-f870-11e6-8c2d-e9faab51db6a.png)

**Comment by philipwalton** [comment]
Thanks for reporting this.

I think this is relatively innocuous, as these errors shouldn't affect anything else on the page, but I'll add some additional logic to catch users who've blocked localStorage access.

FYI: it seems like this error is specific to a setting enabled on an individual user's machine.
http://stackoverflow.com/questions/13102116/access-denied-for-localstorage-in-ie10

**Comment by tinovyatkin** [comment]
It will not affect if autotrack is separated into indepent file, but will stop the execution if autotrack is ES6 imported into common bundle.
Access error also appear in Safari private browsing mode, so, any localStorage access unfortunately must always be wrapped into try/catch

**Comment by philipwalton** [comment]
Ahh, you're right. I actually checked my error reports and saw a number of issues with Safari on iOS. #145 should fix this.
