### ISSUE TITLE
UglifyJs Syntax Error

### ISSUE THREAD

**Issue by Kikobeats** [googleanalytics/autotrack#143]
Hello,

First of all, awesome helpers. Thanks for that.

Second, I'm requering the modules as your docs recommend:

```jsx
import 'autotrack/lib/plugins/outbound-link-tracker'
import 'autotrack/lib/plugins/clean-url-tracker'
import 'autotrack/lib/plugins/max-scroll-tracker'
import 'autotrack/lib/plugins/page-visibility-tracker'
import 'autotrack/lib/plugins/url-change-tracker'
```

My problem is when I run webpack for create the final bundle:

```
ERROR in assets/js/bundle.js from UglifyJs
SyntaxError: Unexpected token: name (UrlChangeTracker) [./~/autotrack/lib/plugins/url-change-tracker.js:28,0][assets/js/bundle.js:2072,6]
```

Any idea why? Could be possible be affected by the Uglify position as loader?

**Comment by philipwalton** [comment]
UglifyJS doesn't support ES2015 code (only ES5), and from the error message it looks like you're not transpiling this to ES5 before running it through UglifyJS. Autotrack source code is written in ES2015, so if you want to `import` it into your project and run it in older browsers, you'll have to make sure to transpile it (via babel or closure compiler or whatever).

A few others have reported similar issues, so I think the documentation probably needs to clarify this a bit better.

You can read more of the discussion here: https://github.com/googleanalytics/autotrack/issues/137

**Comment by Kikobeats** [comment]
I did it, but still didn't work. I'm using Webpack 2.x

**Comment by philipwalton** [comment]
Can you paste your webpack configuration here?

It should look something like this (taken from my [analyticsjs-boilerplate](https://github.com/philipwalton/analyticsjs-boilerplate) repo):
https://github.com/philipwalton/analyticsjs-boilerplate/blob/master/webpack.config.js#L20

**Comment by Kikobeats** [comment]
Of course, you can check here:
https://gist.github.com/Kikobeats/1840434e20374d5fade6a3b49e040a8a#file-webpack-config-js-L40

**Comment by philipwalton** [comment]
Ahh, I think the problem is you're using `include`. As far as I know, when you use `include`, `exclude` is ignored. You have to use one or the other.

**Comment by Kikobeats** [comment]
why not ship the module prepare for be used? I don't understand this over engineering

**Comment by philipwalton** [comment]
See the discussion here: https://github.com/googleanalytics/autotrack/issues/137#issuecomment-280481249

**Comment by Kikobeats** [comment]
You're right, looks need to use just `exclude`:

```
test: /\.(js|jsx)$/,
exclude: /node_modules\/(?!(autotrack|dom-utils))/,
use: ['babel-loader']
```

I added the include but actually is not necessary; Oh Jesus, webpack is so useful but the config... dammit.

Thanks for the library, It's super useful ❤️
