### ISSUE TITLE
Add missing "data-event-noninteractive" and "data-event-social-path"

### ISSUE THREAD

**Issue by phildpearce** [googleanalytics/autotrack#15]
Add missing "data-event-noninteractive"
https://github.com/googleanalytics/autotrack/blob/master/lib/plugins/event-tracker.js

Add missing "data-event-social-path"
https://github.com/googleanalytics/autotrack/blob/master/lib/plugins/social-tracker.js

Thanks

Phil.

Copied from here:
https://plus.google.com/+JimGianoglio/posts/DKvR95C8MWJ

**Comment by philipwalton** [comment]
I kind of touch on this in #11, but in a future version I'm planning to support declaratively adding any valid analytics.js field, which should give you what you want here.

FWIW, social path isn't a valid field, if you meant [`socialTarget`](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#socialTarget), that field is already supported.

**Comment by phildpearce** [comment]
Ok, noted about the full analytics.js field reference :)

No, I do not mean socialTarget. "social-path" was an optional field, but looks like it has been depreciated recently: https://developers.google.com/tag-manager/reference#social-names

**Comment by philipwalton** [comment]
This can now be done in version 1.0 via one of the [common options](https://github.com/googleanalytics/autotrack/blob/1.0.0/docs/common-options.md).
