### ISSUE TITLE
Autotrack import throws Webpack UglifyJsPlugin parse error.

### ISSUE THREAD

**Issue by gregbown** [googleanalytics/autotrack#153]
Angular 4.0.0-rc.2 TypeScript 2.2.1 Autotrack 2.0.4 Webpack 2.2.1
Using require('autotrack'); or import 'autotrack'; causes the following after compile.
ERROR in /scripts/app/main.bundle.js from UglifyJs
SyntaxError: Unexpected token operator «=», expected punc «,» 

Removing the UglifyJs plugin from the Webpack build removes error so I believe this is an issue with the plugin.

I am not sure if it is related to this issue? 
[https://github.com/webpack/webpack/issues/1542](url)

Any direction would be appreciated. Thank you

**Comment by philipwalton** [comment]
It's related to issue #137. Autotrack source code is written as ES2015, so you need to transpile it before using Uglify.
