### ISSUE TITLE
Add optional  event-id, event-entity-type and event-action-type

### ISSUE THREAD

**Issue by phildpearce** [googleanalytics/autotrack#16]
Add optional  "event-id, event-entity-type, event-action-type"
data-event-id="12345"
data-event-entity-type="component"
data-event-action-type="click" 
https://github.com/googleanalytics/autotrack#using-individual-plugins

User-case: event-id is needed for auto-QA testing, and event-action-type=onclick | onload is needed for determining nonInteractive value.

Thanks

Phil.

Copied from here:
https://plus.google.com/+JimGianoglio/posts/DKvR95C8MWJ

**Comment by philipwalton** [comment]
I don't understand this use case. How is the event ID needed for QA testing? Also, there's no event ID field in analytics.js, so I'm not sure what this would get translated to.

**Comment by phildpearce** [comment]
On large GAP implementations with 200+ events, I always use a manually generated eventID  integer which is then lookedup via GoogleSheets via GA reporting API. 

That is manually added to all events in GTM/GA as a hit level dimension. It makes it easily to spot where events have stopped tracking or are returning the wrong values, and it is much more robust than matching on eventCat/Act/Label which can have foreign language values.

Note: there is talk of exposing the {{tagID}} in GTM which would be the same as the eventID.

**Comment by philipwalton** [comment]
This can now be done in version 1.0 via one of the [common options](https://github.com/googleanalytics/autotrack/blob/1.0.0/docs/common-options.md).
