### ISSUE TITLE
maxScrollTracker not working

### ISSUE THREAD

**Issue by patrickew** [googleanalytics/autotrack#161]
Hello there, congrats for this great project!

I can't get maxScrollTracker to work properly. I followed the documentation and this guide to set up a custom metric and a calculated metric: http://jareddillard.com/blog/capturing-max-scroll-length-with-google-analytics.html

After setting up the custom metric, calculated metric and the custom report, I am always getting a "0%" for Avg. Max Scroll Percentage in the report.

As it's the first custom metric in my Google property, I added to the GA code:

```
ga('require', 'maxScrollTracker', { 
  maxScrollMetricIndex: 1, 
});
```

Are there any additional resources for setting up the maxScrollTracker? Any hints are highly appreciated! Thank you

**Comment by philipwalton** [comment]
Hmmm, that post covers it pretty well (thanks @jdillard, great explainer!). Without seeing your complete implementation, it's hard to say what could be going wrong.

Is your code live on a site somewhere I could look at?

**Comment by patrickew** [comment]
The setup worked great. I had been looking at the data from the previous day where the plugin wasn't installed yet. Today the averages appeared. Sorry and thanks!
