### ISSUE TITLE
Add Support for Google Optimize

### ISSUE THREAD

**Issue by stanidesis** [googleanalytics/autotrack#166]
I'd love to see support for the Optimize requirements now that it's made available to all GA users.

The relevant snippets are here: [https://support.google.com/360suite/optimize/answer/6262084#example-combined-snippet-with-ph](https://support.google.com/360suite/optimize/answer/6262084#example-combined-snippet-with-ph)

**Comment by philipwalton** [comment]
You can already use optimize with autotrack today, nothing is preventing you from including both.
