### ISSUE TITLE
eventTracker only recognizing http://

### ISSUE THREAD

**Issue by amramajeed** [googleanalytics/autotrack#168]
The below link fires the event correctly

```
<a href="http://mysite.com/someurl" ga-on="click,auxclick,contextmenu" ga-event-label="/someurl"
	    		ga-event-category="Category text"
	    >My link</a>
```
However the two below links don't:

```
<a href="https://mysite.com/someurl" ga-on="click,auxclick,contextmenu" ga-event-label="/someurl"
	    		ga-event-category="Category text"
	    >My link</a>

<a href="/someurl" ga-on="click,auxclick,contextmenu" ga-event-label="/someurl"
	    		ga-event-category="Category text"
	    >My link</a>
```
Here is my script:

```
  <script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;

if (drupalSettings.ga.id) {
    ga('create', drupalSettings.ga.id, 'auto');	
	ga('require', 'eventTracker', {
	  events: ['click', 'auxclick', 'contextmenu']
	});
	ga('require', 'outboundLinkTracker', {
	  events: ['click', 'auxclick', 'contextmenu']
	});	
    ga('send', 'pageview');
  }
</script>
```

Is this the default behaviour, that only links that begin with http:// fire the events? https and relative urls are not firing the event in my case.

**Comment by philipwalton** [comment]
No, this is not the default behavior. In fact, if you look at the `outboundLinkTracker` [test fixtures](https://github.com/googleanalytics/autotrack/blob/master/test/e2e/fixtures/outbound-link-tracker.html#L14), you'll see they all use `https`.

I tried using your exact code example in my test file and saw events from both the `eventTracker` and `outboundLinkTracker` plugins.

Maybe something else is going on that's preventing your code from working as expected?

**Comment by amramajeed** [comment]
Thanks for the reply.

I noticed that google tag manager is installed on the webpage, for use by adsense.

```
<script async='async' src='https://www.googletagservices.com/tag/js/gpt.js'></script>
<script>
var googletag = googletag || {};
googletag.cmd = googletag.cmd || [];
</script>
<script>
googletag.cmd.push(function()
{ // google ad details }
);
</script>
```
Could this somehow be interfering with the eventTracker ?

**Comment by philipwalton** [comment]
Possibly, is the page live anywhere so I can test it?

**Comment by amramajeed** [comment]
unfortunately no.

I will try to remove the various JS scripts on the page one by one, to see if any of them are affecting the eventTracker.

Thanks again for your help.

**Comment by amramajeed** [comment]
I made a test file to check why the events weren't firing. ( test.txt attached, it was test.html but uploading html isn't allowed).

The page view and outbound link tracker are both working fine, the event tracker has some issues.

The file shows 2 problems:

1. Adding multiple events to the same anchor causes no events to fire at all
2. Adding the hitFilter option option also causes no events to fire at all

This works:

```
<a href="/help"
		  ga-on="click"
		  ga-event-label="/help"
		  ga-event-category="Help Link">
		  The click event works
		</a>
```

This doesn't work:

```
<a href="/help"
		  ga-on="click,auxclick,contextmenu"
		  ga-event-label="/help"
		  ga-event-category="Help Link">
		  Adding multiple events doesn't work
		</a>
```

This works (fires all events successfully, only if single event is specified):

```
ga('require', 'eventTracker', {
				  events: ['click', 'auxclick', 'contextmenu']
				});
```

This doesn't work (no events fired at all):

```
ga('require', 'eventTracker', {
  events: ['click', 'auxclick', 'contextmenu'],
  hitFilter: function(model, element, event) {
    model.set('eventAction', event.type, true);
  }
});
```

Please let me know if any clarification is required.

[test.txt](https://github.com/googleanalytics/autotrack/files/910071/test.txt)

**Comment by philipwalton** [comment]
Your demo page works for me, even if I uncomment the middle section.

Are you sure you're using the most recent version of autotrack? That was the only thing I couldn't test from your page because you're linking to a local copy. 

I replaced your script with this one (just to test), and it worked, which makes me think maybe you're using an older version?

```html
<script src="https://rawgit.com/googleanalytics/autotrack/2.3.1/autotrack.js"></script>
```

**Comment by amramajeed** [comment]
I see the problem now.

The event tracker worked correctly when I copied the lib folder next to the autotrack.js file.

I understood from the docs that only the autotrack.js file should be copied to the project. That was further confirmed when the outboundLinkTracker worked without issues even when the lib folder was not included. It was only when I started using the eventTracker that these issues showed.

Should the entire lib folder be copied to the project alongside the script ? 

Perhaps update the docs to make it clear that the lib folder should be included, so other people won't repeat my mistake.

Thanks for your efforts in helping me resolve this.

**Comment by philipwalton** [comment]
I'm glad you got it working.

The recommended way to install the library is to include the full script as is, use the build tool to create a [custom build](https://github.com/googleanalytics/autotrack#custom-builds), or[ install it via npm ](https://github.com/googleanalytics/autotrack#loading-autotrack-via-npm)as described in the docs. I wouldn't recommend copying files manually, as that takes more work and is more error prone.
