### ISSUE TITLE
Add auto "tel:" and "mailto:" event tracking

### ISSUE THREAD

**Issue by phildpearce** [googleanalytics/autotrack#17]
Add auto "tel:" and "mailto:" event tracking for...

```
<span id="telephoneNumber1" itemprop="telephone">
<a href="tel:+44123400000">+44 (0)1234 00000</a>
</span>
```

Thanks

Phil

Copied from here:
https://plus.google.com/+JimGianoglio/posts/DKvR95C8MWJ

**Comment by philipwalton** [comment]
This is an interesting idea, thanks. I'll have to spend some time thinking about how to best expose this.

**Comment by nekromoff** [comment]
easier done via tag manager btw

**Comment by robwent** [comment]
What about checking for any protocol that isn't http/s so it could include anything else?

http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

**Comment by flawlesswalrus** [comment]
There seem to be some issues with links with "javascript:" in the href.  A bit more details here: [https://github.com/googleanalytics/autotrack/issues/45](https://github.com/googleanalytics/autotrack/issues/45)

**Comment by philipwalton** [comment]
In version [0.6.4](https://github.com/googleanalytics/autotrack/releases/tag/0.6.4) I added a check to only track http(s) protocols by default. This can be overridden via the [`shouldTrackOutboundLink`](https://github.com/googleanalytics/autotrack#shouldtrackoutboundlink) config option to track other protocols as well.
