### ISSUE TITLE
Auxclick and hitFilter option not working for eventTracker plugin

### ISSUE THREAD

**Issue by EluruPrakash** [googleanalytics/autotrack#170]
Default click behavior is working fine,but when trying to use list of events like auxclick,click we are seeing any data getting captured not even the click.In the same way when hitFilter is used default behavior is also not working.Can someone help us with this issue.

**Comment by amramajeed** [comment]
I had the exact same problem a couple of days ago.

I was because the /lib folder needs to be present next to the autotrack.js file.

**Comment by EluruPrakash** [comment]
Instead of adding Js file on the page ,I am doing that using  tag management tool by adding the autotracker js code from a tag.Everything is working fine ,except the above mentioned options ,can someone help me what should be done to get this resolved.

**Comment by philipwalton** [comment]
Is your code live somewhere where I could take a look?

**Comment by EluruPrakash** [comment]
We have implemented it on one of our dev environment ,Its not accessible outside our network.So I can provide the url when we push it to any our production environments

**Comment by philipwalton** [comment]
@EluruPrakash cool, once it's live, let me know and I'll take a look. Alternatively you can push it to a staging server and I can look at it so you don't have to push a broken version to production.

**Comment by EluruPrakash** [comment]
@philipwalton ,thank you philp,but the thing is our staging is not accessible outside of our network.Once we push it to production using our dev space ,will let you know ,so that you can help us.

**Comment by EluruPrakash** [comment]
@philipwalton And one more thing philip for cleanUrlTracker when ever qurey string is not available dimension is carrying a value (not set),is there a way we can overcome that.Can you please help us with this as well ,Thanks for understanding.

**Comment by philipwalton** [comment]
@EluruPrakash you can use the `fieldsObj` options:
https://github.com/googleanalytics/autotrack/blob/master/docs/common-options.md#fieldsobj

**Comment by EluruPrakash** [comment]
@philipwalton Thank you ,using fleldsObj options worked out.

**Comment by philipwalton** [comment]
Great! Glad you got it working.

**Comment by EluruPrakash** [comment]
@philipwalton This  is with respect to outboundLinkTracker where we have a option called shouldTrackOutboundLink which gives an option to provide the list of domains to be considered for tracking ,but our requirement is to exclude a list of domains which should not be considered as outbound link ,I tried modifying the above option itself but its not giving me the expected output ,Can you please help me with this ,and below is the code is tried.
shouldTrackOutboundLink: function(link, parseUrl) {
    var href = link.getAttribute('href') || link.getAttribute('xlink:href');
    var url = parseUrl(href);
   var outboundtrackstatus="";
     if(/(legacy|fuelfix)\.com$/.test(url.hostname)){outboundtrackstatus="false";}
      else{outboundtrackstatus="true";}
   return outboundtrackstatus;
  }
}

**Comment by philipwalton** [comment]
Looks like you're returning the string `"true"` or `"false"` instead of the boolean `true` or` false`. Could that be it?

**Comment by EluruPrakash** [comment]
@philipwalton Yes Yes I think I missed that ,I will check that once ,Thank you.

**Comment by EluruPrakash** [comment]
@philipwalton Thank you ,Its working now.

**Comment by EluruPrakash** [comment]
Hi Philpwalton,in the cleanUrlTracker Plugin we are using stripQuery true as our client needs that ,but because of that Google analytics built-in feature Site search tracking is not happening ,Is there a solution for this ,can you please provide your suggestions on this.
