### ISSUE TITLE
Outbound Link documentation weirdness

### ISSUE THREAD

**Issue by chrisblakley** [googleanalytics/autotrack#173]
Some weird syntax is appearing throughout the usage for the [Outbound Link documentation](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/outbound-link-tracker.md) (maybe from a rouge find/replace?).

Here's one instance, but it happens in all of the implementation sections (towards the bottom):
```js
ga('require', 'outboundLinkTracker');, 'outboundLinkTrackeren">ga('require', 'outboundLinkTracker');
```

I can't find an old commit without that issue appearing and I've gone back as far as the /docs directory existed.

**Comment by philipwalton** [comment]
Can you link to where you're seeing this? I'm having trouble finding it.

**Comment by chrisblakley** [comment]
As soon as I read your reply I knew exactly what happened- I had installed
an extension that must have altered that file when I was viewing it. I've
removed it and the file is fine. Sorry about that.

**Comment by philipwalton** [comment]
No worries. Glad you got it figured out!
