### ISSUE TITLE
autotrack.js Problem in safari browser

### ISSUE THREAD

**Issue by Arinrockcy** [googleanalytics/autotrack#174]
hi, i have a problem with autotrack.js, in safari browser , it preventing the default action of button click.

**Comment by philipwalton** [comment]
Can you provide more details? I can't help unless you give me specifics.

**Comment by Arinrockcy** [comment]
/*! autotrack.js v1.1.0 */ hi , i am using this library version, i have added this code to track all the clicks in my website. var is_safari = navigator.userAgent.indexOf("Safari") > -1;
if (analyse != "off" && typeof(cj_ga_prop_id) != "undefined") {
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', cj_ga_prop_id, 'auto');
    if(!is_safari){
        ga('require', 'outboundLinkTracker', {shouldTrackOutboundLink: function(link, parseUrl) { return true;}});
    }
    ga('send', 'pageview');
} else {
    console.log("GA Tracking disabled!");
}

function ga_event(category, action) {
    var label = (arguments[2]) ? arguments[2] : undefined;
    if (analyse != "off" && typeof(cj_ga_prop_id) != "undefined") {
        ga('send', 'event', category, action, label);
    } else {
        console.log("ga event:- " + category + ", " + action + ", " + label);
    }
}

**Comment by Arinrockcy** [comment]
then the problem i had issue with safari. when ever i click on link or button , it opens all in new tab, so i figured out that the library modifying my anchor tag attribute to _blank, so it all happend because of  navigator.sendBeacon||(e.target="_blank"); , and i came to know that, sendBeacon  will not support for the IOS. i wanted to fix this. is there any other way to do this?

**Comment by Arinrockcy** [comment]
when i used new version, it came with new issue , it basically PreventDefault actions of button. using this a.defaultPrevented || (a.preventDefault(), i am forcing autotrack js to listen all click events.is there any way to do it for IOS browser

**Comment by Arinrockcy** [comment]
[customga.js.zip](https://github.com/googleanalytics/autotrack/files/995304/customga.js.zip)
this is how i modified

**Comment by philipwalton** [comment]
I'm still not sure what you're asking.

Button clicks should not be affected by this plugin. Link clicks in browsers that don't support `navigator.sendBeacon` have their default action prevented so browser can ensure the hit is sent before opening up the new page.

Please describe the problem you're seeing, or (if it's online somewhere) send me a link so I can test it out.

**Comment by Arinrockcy** [comment]
http://sandbox8.advizz.me/content/

**Comment by Arinrockcy** [comment]
you can check in safari

**Comment by philipwalton** [comment]
I'm clicking on outbound links in Safari and I'm seeing the hits being sent.

I'm not sure what exactly you're seeing that's wrong, but unless you can clearly state exactly how to reproduce the behavior you're seeing, I'm going to close this issue as it's not reproducible.

**Comment by Arinrockcy** [comment]
hi, good morning, it opens every links in new tab.

**Comment by philipwalton** [comment]
You are using an old version of autotrack. Please upgrade as this behavior [has changed in more recent versions](https://github.com/googleanalytics/autotrack/blob/master/docs/upgrading.md#updates-and-bug-fixes).
