### ISSUE TITLE
No maxScrollTracker events in 'Real time / Events' tab in GA dashboard

### ISSUE THREAD

**Issue by amit1911** [googleanalytics/autotrack#175]
I am able to see other events like breakpoint, impressions, etc. but there are no maxscroll events in the Real-time/Events tab. My configuration is as follows:-
```
ga('require', 'maxScrollTracker');
```

**Comment by philipwalton** [comment]
There are tons of reason why this might not work, and without more details it's hard to say.

One thing that immediately comes to mind is: once you scroll to 100%, no more scroll events are sent in that session. That means if you visited the page, scrolled to the bottom, then went to the real time view to check for events you might have missed them.

Also, I strongly recommend against using the real time view for debugging. Use this instead:
https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging

**Comment by amit1911** [comment]
Actually I noticed that the events are being fired but it's just that not all events are displayed under REAL-TIME/events section. I have a few social events and they are also not showing. I confirmed that events are being fired using the google analytics debug file. Can you tell me how can I see all the events that are being fired in the google analytics dashboard?

**Comment by philipwalton** [comment]
Glad to hear the hits are actually sending.

[Social hits](https://developers.google.com/analytics/devguides/collection/analyticsjs/social-interactions) (i.e. not [event hits](https://developers.google.com/analytics/devguides/collection/analyticsjs/events)) don't show up in the Real Time dashboard. If you really want to see them in the Real Time dashboard then you should send them as event hits instead (this is what I do).
