### ISSUE TITLE
IPHONE safari issue

### ISSUE THREAD

**Issue by Arinrockcy** [googleanalytics/autotrack#178]
auto track  disabled my website button click .
https://sandbox6.advizz.me/content/
try log in, or try subscribe to our newsletter

**Comment by philipwalton** [comment]
You're going to have to be specific about what exactly doesn't work. The functionality seems to work when I try.

**Comment by Arinrockcy** [comment]
ok, https://sandbox6.advizz.me/login/ go this url and then select any login type. then click the button SIGN IN. button click is disabled by the autotrack it happening only in safari and iphone browsers.  to see the different  https://sandbox7.advizz.me/login/ you can cross check here. it is happening only after updating my autotrack lib to new version. i hope it can help you understand.

**Comment by Arinrockcy** [comment]
no response

**Comment by philipwalton** [comment]
@Arinrockcy when I go to that site on Safari on an iPhone I can click the sign in button, and everything appears to be working (I get an error saying my username/password don't match, but that's expected).
