### ISSUE TITLE
mediaQueryTracker event is not fired

### ISSUE THREAD

**Issue by Tiendq** [googleanalytics/autotrack#183]
I implemented `mediaQueryTracker` as below code in my website (with GTM). But when I tested it in GTM's Preview mode, there is no `mediaQueryTracker` event fired in GA Realtime's Events report when I changed browser window size.

Though other events e.g. `outboundLinkTracker` worked well.

```javascript
<script>
  window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
  
  ga('create', {{gaid}}, 'auto', {
    allowLinker: true
  });

  ga('require', 'linker');
  ga('require', 'cleanUrlTracker');
  ga('require', 'eventTracker');
  ga('require', 'outboundLinkTracker');

  ga('require', 'mediaQueryTracker', {
    definitions: [{
      name: 'Breakpoints',
      dimensionIndex: 18,
      items: [
        { name: 'xs', media: 'all' },
        { name: 'sm', media: '(min-width: 576px)' },
        { name: 'md', media: '(min-width: 768px)' },
        { name: 'lg', media: '(min-width: 992px)' },
        { name: 'xl', media: '(min-width: 1200px)' }
      ]
    }]
  });

  ga('send', 'pageview');
</script>
<script async src="https://www.google-analytics.com/analytics.js"></script>
<script async src="/libs/autotrack.js"></script>
<!-- End Google Analytics -->
```

**Comment by philipwalton** [comment]
That code looks correct to me, so the issue must be somewhere else and it's impossible for me to know.

Have you tried using the debugger? It's much better than deploying to your live site and debugging with the real time view.
https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging

**Comment by Tiendq** [comment]
@philipwalton You're correct, events were not appeared in Realtime view (why?) but collected in a custom report which I could see now (a day delayed data). Thanks.
