### ISSUE TITLE
Broken links in Safari after back button

### ISSUE THREAD

**Issue by mgladdish** [googleanalytics/autotrack#184]
I've just tried to use autotrack on my site and come up against a really nasty bug in desktop Safari.

1) Use outboundLinkTracker
2) Follow external link from site
3) Following link seems to take a while, but does navigate to external page OK and click is registered in google analytics OK
4) Use the browser back button to go back to my site
5) *Every other link, even internally within my site, now sends me to the external link I followed*

**Comment by philipwalton** [comment]
Ahh, this is a nasty bug indeed!

It looks like Safari doesn't always unload the page when navigating away, so event handlers that weren't properly removed stick around when you navigate back (no other browser does this as far as I know).

I've taken a look at the code and I think I can fix this issue by just removing the event handler immediately prior to loading the next page.

> Following link seems to take a while...

It looks like there was also an issue where Safari was not calling the `hitCallback` function and just waiting for the timeout (which was 2 seconds), so I think that explains the delay you're seeing. I'll fix that as well.

**Comment by philipwalton** [comment]
This should be fixed in version [2.4.1](https://github.com/googleanalytics/autotrack/releases/tag/2.4.1). Let me know if you're still seeing the issue.
