### ISSUE TITLE
What is the best way to pass common data on each event

### ISSUE THREAD

**Issue by amit1911** [googleanalytics/autotrack#186]
I would like to pass some generic information for each and every event. By event i mean events belonging to any of the autotrack plugins (impressionTracker, eventTracker, etc.). The only way i can think of right now is to use hitFilter to pass data using custom metrics for each of the plugins. Is there a better way?
Example scenario - I have an application that has multi language support and i would like to know what events were fired for each language so how do i pass the current application language for each and every event?

**Comment by philipwalton** [comment]
Do you want this information to be passed with *all* hits, including hits sent by non-autotrack plugins? If so you can use the [set](https://developers.google.com/analytics/devguides/collection/analyticsjs/accessing-trackers#updating_tracker_data) command or look into using one of the [tasks](https://developers.google.com/analytics/devguides/collection/analyticsjs/tasks) (which is what the autotrack `hitFilter` option uses under the hood).

If you only want it to be sent with autotrack plugins, then I'd use either the `hitFilter` or `fieldsObj` options for autotrack plugins. Note that if your main concern is just not repeating yourself you can always just define them once on a variable and pass that to each of the plugins.

**Comment by amit1911** [comment]
Yes, i want this information to be passed on all hits. Currently all the plugins have slightly different hitFilters so i cannot define a common hitFilter function and pass it to the rest. I will probably have to define a function that takes the model and adds custom data to it and call this function in all the hitfilters. Something like the following
```
const passCommonHitData = (model, store) => {
    model.set('dimension3', store.getState().quiz.lang, true);
}

hitFilter: function(model, element, event) {
        if (!element.dataset.eventAction) {
            model.set('eventAction', event.type, true);
        }
        passCommonHitData(model, store);
    }
```

But I thought maybe there is a common hitFilter type functionality for all the plugins which will make it easier.

But I have another problem. The above works fine for all the autotrack plugins, but sometimes I fire a hit programmatically using
```
ga('send', {
    hitType: 'event',
    eventCategory: 'report',
    eventAction: 'something'
});
```
in this case the hitFilter won't be called and the common data will not be sent. I need to handle this case as well. Do you know how I can do that?

**Comment by philipwalton** [comment]
> But I thought maybe there is a common hitFilter type functionality for all the plugins which will make it easier.

No, sorry, there is not a common `hitFilter` for all plugins.

> in this case the hitFilter won't be called and the common data will not be sent. I need to handle this case as well. Do you know how I can do that? I am new to GA. Thanks for your help.

 analytics.js [tasks](https://developers.google.com/analytics/devguides/collection/analyticsjs/tasks) should be able to help you in this case. They allow you to hook in to all hits sent from the current tracker.

I'd start by overriding the `buildHitTask`, as it is most likely what you want for your use case.

**Comment by amit1911** [comment]
thanks a lot...i think buildHitTask is what i needed. Now I don't even have to modify individual hitfilter function; i can just override the buildHitTask to pass all the common data.
