### ISSUE TITLE
outboundFormTracker not working

### ISSUE THREAD

**Issue by EluruPrakash** [googleanalytics/autotrack#187]
Hi ,We have tried using outboundformtracker plugin on one of the form submit available on our site .But we could not see any data coming out when a form is submitted.Can you please help us with this issue.
We tried using without any customizing but still nothing worked out .Below is the code we have used.
window.ga('hnp.require', 'outboundFormTracker');

**Comment by philipwalton** [comment]
Is that the only code you used? Did you load the autotrack library?

Please provide more information or it's impossible for me to help. And if the code is hosted on a live site somewhere, reply with the URL and I can take a look.

**Comment by EluruPrakash** [comment]
Yes Philip we have loaded the autotrack library ,other plugins like cleanUrlTracker,outboundlinkTracker are working as expected but the issue is only with formsubmitTracker ,will push the code to one of our environment and would provide you with the details,Thanks for your support.

**Comment by philipwalton** [comment]
Also make sure you've taken a look at the analytis.js debugger here:
https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging

**Comment by EluruPrakash** [comment]
Hi Philip we have pushed the formtracker code on the below page and also here is the code we have used.
 window.ga('hnp.require', 'outboundFormTracker', {
        shouldTrackOutboundForm: function(form, parseUrl) {
          console.log("outboundformTracker executed");
          var url = parseUrl(form.action);
          return /(monster)\.com$/.test(url.hostname);
        }
      });
http://www.chron.com/jobs/

When user clicks of the "Search"button ,outboundFormtracker is expected to trigger an event.
Can you please have a look and help us with this issue.

**Comment by philipwalton** [comment]
It looks like you're returning `false` from a jQuery event handler on `click` for that button in some of your other code, which is stopping the event from propagating as well as preventing the default submit action.

And if there's no submit action, that means autotrack's `outboundFormTracker` plugin can't track it.

If you want this to work you'll have to refactor your site code to change this behavior, there's unfortunately nothing I can do on my side to help you here.
