### ISSUE TITLE
Wont work with angular cli

### ISSUE THREAD

**Issue by mackelito** [googleanalytics/autotrack#195]
When importing autotrack I get this error when building.

ERROR in vendor.999452ff7d973a3cf95e.bundle.js from UglifyJs
Unexpected token: name (toAdd) [/Users/arket/node_modules/autotrack/lib/usage.js:78,0][vendor.999452ff7d973a3cf95e.bundle.js:20744,8]
error Command failed with exit code 1.

**Comment by philipwalton** [comment]
Not sure why you close this, but in case it's helpful, this could be related to #137.

**Comment by mackelito** [comment]
Yes.. that was the problem.. still not solved for me but not a bug in autotrack :P
