### ISSUE TITLE
Honor DoNotTrack

### ISSUE THREAD

**Issue by DirtyF** [googleanalytics/autotrack#198]
Hi,

Would you consider to honor DNT in `autotrack` or is it something that should be implemented outside of this lib?
https://www.w3.org/2011/tracking-protection/drafts/tracking-dnt.html#js-dom

Thanks.

**Comment by philipwalton** [comment]
That would have to be a feature request for `analytics.js` since ultimately that's the library that's doing the sending of data. Autotrack just tells analytics.js additional things to send.

You can find the public GA issue tracker here:
https://issuetracker.google.com/issues?q=componentid:187400
