### ISSUE TITLE
maxScrollTracker: custom metric format

### ISSUE THREAD

**Issue by EW0JY** [googleanalytics/autotrack#208]
Hey,

quick question: does the custom metric format have to be percentage, or integer? As far as I understand the documentation it's a percentage, but then again and integer value would make sense as well, (0-100)

Thanks!

**Comment by EW0JY** [comment]
sorry, my bad, the option "percentage" doesn't even exist in GA, so I guess it's integer :)...

**Comment by philipwalton** [comment]
Yeah, it's an integer, though if you use a [calculated metric](https://support.google.com/analytics/answer/6121409?hl=en) you can set the format to percentage.
