### ISSUE TITLE
outboundLinkTracker

### ISSUE THREAD

**Issue by Domgarth** [googleanalytics/autotrack#217]
I initialise as follows

ga('require', 'outboundLinkTracker', {
  events: ['click', 'auxclick', 'contextmenu']

When I right click (contextmenu), it records the outbound click in Analytics even if I do not actually do an outbound click e.g i do not select  "Open Link in new tab"

Is this the expected behaviour ?

**Comment by philipwalton** [comment]
Yes, this is the intended behavior.

There's no observable event for what action (if any) a user takes after right-clicking and opening up the context menu, so the best we can do is record how often that happens.

**Comment by Domgarth** [comment]
I thought that maybe it just captured the right-click on the outbound link
rather than the actual outbound link.
Thanks for the confirmation.
