### ISSUE TITLE
Can I post here?

### ISSUE THREAD

**Issue by JDutil** [googleanalytics/autotrack#223]
I keep receiving `You can't comment at this time.` error messages from Github, but I'm allowed to comment all over the place in other repos.  I'm trying to comment on #222 saying:
> To work around this I changed my import from `autotrack` to `autotrack/autotrack` as suggested [here](https://github.com/googleanalytics/autotrack/issues/137#issuecomment-290238077)

The thread does not appear to be locked, but I can't comment... Is there some sort of Github feature blocking users from commenting on repos I'm unaware of you're using or is Github just failing to post here?

**Comment by philipwalton** [comment]
This could be because of a browser extension? I've heard reports before of people having trouble with Github due to browsers extensions blocking form requests with words like "analytics" or "track" anywhere in the request body.

**Comment by JDutil** [comment]
@philipwalton I use uMatrix as an ad blocker, and it does block everything by default, but I've already whitelisted everything but wait for it Google Analytics on Github so that shouldn't be the issue... Unfortunately I can't comment directly on this issue, but let me try an email response.

**Comment by JDutil** [comment]
I guess you can close my issues as ad blocker related, but I’ve ironically whitelisted everything besides GA with my browser extension…

**Comment by JDutil** [comment]
Thanks, sorry for the confusion. :beers:
