### ISSUE TITLE
Can't close my own issues.

### ISSUE THREAD

**Issue by JDutil** [googleanalytics/autotrack#225]
Tried to close my issues #223 & #224 but apparently I'm not allowed to close them. Sorry contributors but this is just stupid. I can comment and close on any other repo just not this one for some unknown reason...

![error in ie 11 issue 222 googleanalytics autotrack](https://user-images.githubusercontent.com/25104/37945443-80d2b6d4-313d-11e8-937a-236c52c0ff1b.png)
![i can open issues but i can t comment issue 224 googleanalytics autotrack](https://user-images.githubusercontent.com/25104/37945448-838c6aaa-313d-11e8-9bf3-b1e5c850d33e.png)

**Comment by philipwalton** [comment]
Closing due to adblock issue, see #223.
