### ISSUE TITLE
AutoTrack and Ad-Blockers Issue

### ISSUE THREAD

**Issue by ayumihamsaki** [googleanalytics/autotrack#238]
Hi,

Been using this library for a few years now and love it. The only issue I got these days is that Ad-Blocker like Adblock Plus block this library and that is a really big issue.

I have been reading to do the following things to get around Ad-Blockers, these are:

1. First, download the Google Analytics JavaScript library itself and host it on your server.
2. Then alter the code in the downloaded library to change the target host from www.google-analytics.com to your own domain name using find-replace.
3. Replace the link from the default Google Analytics script in your codebase to modified one.
4. Create a proxy endpoint to Google Analytics servers on your back end. One important step here is to additionally detect the client’s IP address and write it explicitly in requests to Google Analytics servers to preserve correct location detection.

Points 1-3 are straight forward and point 4 is suggesting to create a server proxy.

As I am using Laravel 5 (which is the most common PHP library), there is a github package out there found here: https://github.com/irazasyed/laravel-gamp

The above package sends the data via the GA Measurement Protocol PHP Library.

Which brings me to AutoTrack, I don't think I can send all the AutoTrack plugin data through that package because you have created your own plugins as such and am I right in thinking that data is not part of the Measurement Protocol API.

As of 2017, 30% of global internet traffic now use an Ad-Blocker, so this is a big issue with regards to this library!

I would love to see an official enhancement to this package to solve this issue!

Also some help or recommendations what would be the best solution with using AutoTrack and by-passing ad-blockers.

(I really don't understand why an Ad-Blocker would block Google Analytics when using `anonymizeIp:true`)

Hopefully @philipwalton is around to give some of his technical insights into this matter,

Thanks.

**Comment by philipwalton** [comment]
Hi @ayumihamsaki, autotrack does use the measurement protocol, so it's not a special case here. If an adblocker is blocking Google Analytics in general, then it's probably blocking autotrack as well. If you adopt a solution to work around the adblocker, it'll probably work for autotrack too.

**Comment by ayumihamsaki** [comment]
Thanks for the info.
