### ISSUE TITLE
Google analytics tracking doesn't require URL request to track a local R Shiny app

### ISSUE THREAD

**Issue by matt-sd-watson** [googleanalytics/autotrack#275]
I have added Google tracking to my R Shiny application as described in this article: 
https://shiny.rstudio.com/articles/google-analytics.html

and deployed the application through a shinyapps.io server as described here: 
https://shiny.rstudio.com/articles/shinyapps.html

The user tracking works as expected for events/user etc., except that Google Analytics is able to track the application when it is run locally through [R Studio IDE](https://posit.co/products/open-source/rstudio/), and doesn't require a URL access to the specific shinyapps.io URL where the app is deployed on the web. 

This means that any local app development and testing conducted by developers on the app will be tracked by Google Analytics, which for our purposes will inflate the tracking statistics and generate many false positives for actual public app activity. 

Is there a way to enforce that the user activity must come through a specific URL to avoid this local tracking? On Google Analytics I have set the specific URL for the app, but it does not seem to work.

**Comment by matt-sd-watson** [comment]
Resolved by modifying internal R code within the app to restrict to non-interactive sessions

**Comment by Kbenge5** [comment]
Sir i need to do alot of things with my account i am waiting for my check i
should have received on the third i need auth and oauth with fido i should
have picked up my device in louisville louisville yesterday i was not able
to pay my verizon when i got paid because i did not get paid my ssi is in
route

Karen benge

**Comment by Kbenge5** [comment]
I need help linking to plaid to my bank accounts i need secure connections

Karen benge
