### ISSUE TITLE
How to notify EventTracker about DOM updates

### ISSUE THREAD

**Issue by chrisppp** [googleanalytics/autotrack#30]
Hi!

I have such simple case:

1. I init EventTracker as usual
2. Later on, I update DOM, ie. I add some new links with data-event-* attributes.

How do I make sure EventTracker binds to click event on these newly inserted links and handle click events properly?

**Comment by philipwalton** [comment]
You don't have to do anything. The `eventTracker` plugin uses event delegation and listens for click events on `document`, so it doesn't matter if the DOM changes.
