### ISSUE TITLE
Can't star project 

### ISSUE THREAD

**Issue by UberGruber** [googleanalytics/autotrack#31]
Sorry it's so peculiar that can't help to wonder why the heck this is happening, and only with your repo, any other project around is just fine.

http://tinypic.com/r/2eewu2g/9.

Is this just an issue with me because I'm speshul or what?

**Comment by philipwalton** [comment]
Hmmmm, that is weird. Is it still happening?

It must be a Github bug because other people seem to be able to, and we certainly haven't turned off any setting like that.

**Comment by UberGruber** [comment]
Oh wow found the problem, uBlock Origin. Can't tell why tho, with any other project is working, but not with this one, is it maybe cause it has some "google" in either some javascript call or something due the repo name? Anyway disabling it did the trick, sorry for this silly nuisance!

**Comment by philipwalton** [comment]
Interesting. Maybe it's because of the word "track" or "analytics". Anyway, glad you got it figured out!
