### ISSUE TITLE
Real-time analytics numbers are around ~10% when this script is active

### ISSUE THREAD

**Issue by chrisabrams** [googleanalytics/autotrack#34]
We've tried deploying this script a few times to our site and have seen the GA real-time tab numbers drop to around 10% of their numbers. As soon as we remove the script, the numbers jump back up.

Is there a setting to get this script to behave correctly with real-time analytics reporting?

**Comment by chrisabrams** [comment]
We just pushed the script back on the site to show you. We are concerned that if the real-time numbers are dropping, that the page view count is also being mis-reported.

**Comment by philipwalton** [comment]
If you use the analytics.js debugger, you can see this happening for yourself:
https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging

**Comment by chrisabrams** [comment]
That was it - using the script from this repo solved it.

**Comment by philipwalton** [comment]
Great! Glad you got it working.

**Comment by chrisabrams** [comment]
Appreciate the quick help! :)
