### ISSUE TITLE
urlChangeTracker doesn't seem to work

### ISSUE THREAD

**Issue by dottodot** [googleanalytics/autotrack#39]
I'm basing this on when I view the real time stats the active page url doesn't change.

I have a Marionette app compiled using browserify so I've tried `require('autotrack')` and a direct link to the autotrack.js file

Here my tracking code snippet.

```
<script>
    window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
    ga('create', 'UA-XXXXX-Y', 'auto');
    ga('require', 'autotrack');
    ga('require', 'ec');
    ga('send', 'pageview');
  </script>
  <script async src='https://www.google-analytics.com/analytics.js'></script>
```

**Comment by philipwalton** [comment]
Did you download the `autotrack.js` file and add it to your site? I don't see that in your code sample.

Also, the best way to debug `analytics.js` issues is to use the [debugger](https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging) or [Tag Assistant](https://ga-dev-tools.appspot.com/tag-assistant/). Using the Real Time view as a way of debugging doesn't always give you all the information, and it means you're sending real hits which will always be in your reports. It's better to test your implementations locally before deploying.

**Comment by dottodot** [comment]
Is say in the documentation you can install using npm and if using browserify require it using `require('autotrack')` so should be not need to at the `autotrack.js` file. I have tried it including the file rather than requiring it but still doesn't work.

On my current implementation, which I am testing locally, I can see real time stats, so I would expect this to do the same thing.

**Comment by philipwalton** [comment]
Yes, you can, I just wanted to make absolutely sure you were doing that. If the autotrack source code never gets added to the page, then all commands after `ga('require', 'autotrack');` will simply not run.

That's why I suggested [using the debug version of analytics.js](https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging), it'll tell you on the console exactly what it's doing and you'll see exactly where the problem is.

**Comment by dottodot** [comment]
OK so here's my debug output, but as I browse my site no pageview commands are being sent

```
Initializing Google Analytics.
analytics_debug.js:9 No plugin url set for "autotrack".
analytics_debug.js:9 Loading resource for plugin: ec
analytics_debug.js:9 Loading script: "https://www.google-analytics.com/plugins/ua/ec.js"
analytics_debug.js:9 Running command: ga("create", "UA-XXXXX-Y", "auto")
analytics_debug.js:9 Creating new tracker: t0
analytics_debug.js:9 Auto cookieDomain found: "none"
analytics_debug.js:9 Running command: ga("require", "autotrack")
analytics_debug.js:9 Waiting on require of "autotrack" to be fulfilled.
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Registered new plugin: ga(provide, "ec", Function)
analytics_debug.js:9 Running command: ga("require", "autotrack")
analytics_debug.js:9 Waiting on require of "autotrack" to be fulfilled.
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Registered new plugin: ga(provide, "eventTracker", Function)
analytics_debug.js:9 Running command: ga("require", "autotrack")
analytics_debug.js:9 Waiting on require of "autotrack" to be fulfilled.
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Registered new plugin: ga(provide, "mediaQueryTracker", Function)
analytics_debug.js:9 Running command: ga("require", "autotrack")
analytics_debug.js:9 Waiting on require of "autotrack" to be fulfilled.
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Registered new plugin: ga(provide, "outboundFormTracker", Function)
analytics_debug.js:9 Running command: ga("require", "autotrack")
analytics_debug.js:9 Waiting on require of "autotrack" to be fulfilled.
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Registered new plugin: ga(provide, "outboundLinkTracker", Function)
analytics_debug.js:9 Running command: ga("require", "autotrack")
analytics_debug.js:9 Waiting on require of "autotrack" to be fulfilled.
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Registered new plugin: ga(provide, "socialTracker", Function)
analytics_debug.js:9 Running command: ga("require", "autotrack")
analytics_debug.js:9 Waiting on require of "autotrack" to be fulfilled.
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Registered new plugin: ga(provide, "urlChangeTracker", Function)
analytics_debug.js:9 Running command: ga("require", "autotrack")
analytics_debug.js:9 Waiting on require of "autotrack" to be fulfilled.
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Registered new plugin: ga(provide, "autotrack", Function)
analytics_debug.js:9 Running command: ga("require", "autotrack")
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Running command: ga("t0.require", "eventTracker", {})
analytics_debug.js:9 Plugin "eventTracker" intialized on tracker "t0".
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Running command: ga("t0.require", "mediaQueryTracker", {})
analytics_debug.js:9 Plugin "mediaQueryTracker" intialized on tracker "t0".
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Running command: ga("t0.require", "outboundFormTracker", {})
analytics_debug.js:9 Plugin "outboundFormTracker" intialized on tracker "t0".
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Running command: ga("t0.require", "outboundLinkTracker", {})
analytics_debug.js:9 Plugin "outboundLinkTracker" intialized on tracker "t0".
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Running command: ga("t0.require", "socialTracker", {})
analytics_debug.js:9 Plugin "socialTracker" intialized on tracker "t0".
analytics_debug.js:9 Executing Google Analytics commands.
analytics_debug.js:9 Running command: ga("t0.require", "urlChangeTracker", {})
analytics_debug.js:9 Plugin "urlChangeTracker" intialized on tracker "t0".
analytics_debug.js:9 Plugin "autotrack" intialized on tracker "t0".
analytics_debug.js:9 Running command: ga("require", "ec")
analytics_debug.js:9 Plugin "ec" intialized on tracker "t0".
analytics_debug.js:9 Running command: ga("send", "pageview")
```

**Comment by philipwalton** [comment]
That all looks good to me.

Have you checked the network tab to see if HTTP requests to `https://www.google-analytics.com/collect` are going out for the pageviews?

![screen shot 2016-03-24 at 12 03 59 pm](https://cloud.githubusercontent.com/assets/326742/14028196/89418e6a-f1b8-11e5-9db2-b392c0530c18.png)

**Comment by philipwalton** [comment]
If they are then the only thing I can say is maybe your GA view settings are filtering them out, or perhaps you're using the wrong tracking ID? It's really hard to say, but if you can verify that pageviews are being sent in the network tab, then that means autotrack is working properly and the issue is somewhere else.

**Comment by dottodot** [comment]
I'm not seeing any requests going out to `https://www.google-analytics.com/collect`

**Comment by philipwalton** [comment]
Do you see any JS errors in the console? What if you break on uncaught exceptions, anything then?

In your debug log I see

```
analytics_debug.js:9 Running command: ga("send", "pageview")
```

So it seems like analytics.js is trying to send a pageview. If you're saying it's not, then something must be stopping it outside of analytics.js. It could be a number of things, and without seeing your setup it's hard to speculate.

Can you upload anything to the web so I could take a look?

**Comment by dottodot** [comment]
Not seeing any errors at all. Here's my test site so you can have a look

http://staging.boxxerworld.com

**Comment by philipwalton** [comment]
Ok, so I think I might have an idea of what's going on. Looking through the minified code, I see the following expression that fires when I click on a link:

```js
Modernizr.history && history.replaceState( ... )
```

It's not clear to me from the minified code if this is part of a library or if this is your application code, but as far as I can tell, you're using `replaceState` instead of `pushState` to update the URL.

Whether rightly or wrongly, autotrack only sends pageviews when code invokes `pushState` or it receives a `popstate` event and the URL is different from the current URL. This explains why urlChangeTracker *doesn't* work when clicking on links on your site, but it *does* work when clicking the back button.

If there are enough people or commonly used libraries doing this in the wild, it might be a good idea to rethink how I detect URL changes...

Can you confirm whether or not this is your application code vs. library code? If it's library code can you tell me what library so I can check it out?

**Comment by dottodot** [comment]
Yes that was it thank you, I was using replaceState to remember the scroll position when going back. Removing this does indeed fix the problem.
