### ISSUE TITLE
Outbound Link Tracking breaks ASP.net __doPostBack() javascript links in IE 11

### ISSUE THREAD

**Issue by flawlesswalrus** [googleanalytics/autotrack#45]
I added autotrack.js to a site that uses ASP.net, which generates links that use "javascript:" in the href attribute:

`<a id="foo_bar" href="javascript:__doPostBack('foo$bar','')">Linked Item</a>`

When clicked, those links attempt to open "javascript:__doPostBack('foo$bar','')" as a URL (whi, and don't execute the javascript.

This only happened to us in IE 11. It worked fine in the latest Chrome and Firefox.

Sorry if I'm not reporting this correctly or well... I'm new to Github (, and I don't totally understand *why* this is happening, I can only confirm that it *is* happening.  I'm just reporting this in case the script can be edited in some way to account for this edge problem.

**Comment by philipwalton** [comment]
Thanks, this was fixed in #44 and released in version [0.6.4](https://github.com/googleanalytics/autotrack/releases/tag/0.6.4)
