### ISSUE TITLE
How does urlChangeTracker work?

### ISSUE THREAD

**Issue by luboskmetko** [googleanalytics/autotrack#53]
First of all, thanks for the great library. I like how easy is to implement it with Browserify.

I'd like to ask how exactly urlChangeTracker works - we'd like to use it for tracking overlays as additional pageviews, eg. /team/#name. So in the overlay code we are using History API and have something like:

`history.pushState({type: "overlay", url: id}, document.title, url + "#" + id);`

But it doesn't seem to generate additional pageviews. Is the problem that only hash portion of the URL changes as mentioned in documentation? I guess so just wanted be sure before messing with URL rewriting.

Thanks

**Comment by luboskmetko** [comment]
Eventually, I've replaced # with ? in our overlays implementation and it works :)

**Comment by philipwalton** [comment]
Yes, the `urlChangeTracker` plugin does not track hash changes. I'm glad you figured it out.
