### ISSUE TITLE
urlChangeTracker changing page to `undefined` in IE11

### ISSUE THREAD

**Issue by beast257** [googleanalytics/autotrack#54]
I've been doing some work on a single-page javascript application that calls `history.replaceState` with only two arguments - the optional URL is unspecified. I've been integrating GA to track visits and some internal events. Since some of our events update the URL to reflect a change in state, I figured it would be nice not to have to manually handle those occasions, and tried using the `urlChangeTracker` plugin to capture those events for me. Works great in Chrome. But I hit a snag in IE11.

The problem seems to be thanks to https://github.com/googleanalytics/autotrack/blob/695b2be7a23f459ccae1624a9c10c3a7eef0dfcd/lib/plugins/url-change-tracker.js#L67 . In particular, the `url` variable is undefined. In Chrome, this works as expected as the undefined variable is passed on and ignored. But IE11, for some reason, treats this as an `undefined` string literal, and my page gets updated from eg `/path/index.html` to `/path/undefined`. So this is a difference in behaviour in how IE11 handles the arguments. I can reproduce it independently of the plugin with the following steps:

1. Visit some website, for example, `http://github.com/`
2. In the dev console, run `var t;`
3. Now run `history.replaceState({}, '', t)`
4. In Chrome, the location doesn't change. In IE11, it changes to `http://github.com/undefined`

In any case, this is of course throwing off my stats tracking. I'm going to get around this in my project my manually tracking the extra events. I imagine others who want a proper workaround for this could override `history.replaceState` themselves prior to running the plugin, using a function that explicitly checks if that third variable is undefined, and if it is, directly calls the original `history.replaceState` with only two arguments instead (which _does_ still work as expected in IE11).

I raise this here to ask if it's worth making such a change in the plugin directly. It might prevent other users having issues like mine in the future.

**Comment by philipwalton** [comment]
Thanks @beast257 for reporting this.

I think this issue should be fixed via #57, which is available in version 0.6.5. Please let me know if you're still having problems after upgrading.
