### ISSUE TITLE
Sending pageview after enhanced ecommerce

### ISSUE THREAD

**Issue by dottodot** [googleanalytics/autotrack#55]
In the enhanced ecommerce documentation is shows sending the page view after sending the data however when using autotrack the pageview is always sent first. I could always send a pageview after my data but I'm assuming that would create a duplicate pageview hit in the stats.

**Comment by philipwalton** [comment]
I'm not sure what documentation you're referring to. Can you provide links?

**Comment by dottodot** [comment]
https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce

**Comment by philipwalton** [comment]
You're going to have to be more specific. When you send the pageview will vary depending on your particular implementation, but all enhanced ecommerce documentation as well as all autotrack documentation suggests requiring the plugins *before* sending the initial pageview.

**Comment by philipwalton** [comment]
Closing due to lack of response.

**Comment by 123ndy** [comment]
I am also wondering about this:

From the [Enhanced Ecommerce documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce), it says that you need to do:
```
ga('ec:addProduct', {
  'id': 'P12345',
  'name': 'Android Warhol T-Shirt',
  'category': 'Apparel',
  'brand': 'Google',
  'variant': 'black'
});

ga('ec:setAction', 'detail');
```
before you do `ga('send', 'pageview');`.

I am using the `urlChangeTracker`. How can I make sure that the `pageview` is sent after `ec:addProduct` and `ec:setAction` is set?
