### ISSUE TITLE
Will autotrack be an official plugin?

### ISSUE THREAD

**Issue by bartekpl** [googleanalytics/autotrack#56]
In [docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/using-plugins#loading_the_plugin_code) there already are some official plugins for GA. Will autotrack be added there? If yes, will it also be available as an option within GTMs GA tag config screen?

**Comment by philipwalton** [comment]
There are no current plans to make autotrack an official plugin or to make it work more easily with GTM. If you're a GTM user, you can already accomplish a lot of this functionality via GTM itself.

Autotrack's primary audience is developers who don't need or want a tag management solution.
