### ISSUE TITLE
Cross domain or *.domain.com is not an Outbound link 

### ISSUE THREAD

**Issue by yamlfd** [googleanalytics/autotrack#64]
I have reviewed your code because of https://www.drupal.org/node/2671716 and found some issues with the code.

That is not the way how oubound need to work.
```
OutboundLinkTracker.prototype.shouldTrackOutboundLink = function(link) {
  return link.hostname != location.hostname &&
      link.protocol.indexOf('http') === 0;
};
```

There is cross domain suppoet in GA and also subdomain support. That means you need to support *,example.com and also a list/array of cross domain hostnames. Outbound is than only if you leave the site and not because you switch from "example.de" to "example.es". In this case you stay on the same site, you only switch the language of the site (cross domain support).

If you switch from www.example.com to shop.example.com you also do not leave the site.

**Comment by philipwalton** [comment]
The `shouldTrackOutboundLink` configuration option is provided so you can customize the outbound link logic yourself, and all the examples you listed above are supported through customization.

The default is a hostname match because that will work for the greatest number of people (i.e. there are a lot more people who host sites on subdomains suchs as wordpress.com or appspot.com than there are people who run a single site that spans multiple subdomains or TLDs).

The existing cross-domain support in analytics.js is not relevant to this issue. That case deals with client IDs, this case deals with links, they are different use cases.

**Comment by yamlfd** [comment]
Are you able to implement the cross domain support nativly like ga does? Not everyone should reinvent the wheel for this standard ga build in stuff.

**Comment by philipwalton** [comment]
> Are you able to implement the cross domain support like ga does? Not everyone should reinvent the wheel for this standard ga build-in stuff.

I have no idea what you mean by this.

And as I said before: the existing cross-domain support in analytics.js is not relevant to this issue. That case deals with client IDs, this case deals with links, they are different use cases.

**Comment by yamlfd** [comment]
I try to explain this. If I go into the Google Analytics website and configure cross domain tracking I need to enter the list of my cross domains. e.g. *.example.com, *.example.net, foo.example.org etc. Based on my entered domain list the tracking code is build and contains these names in a settings array.

e.g.
`
ga('linker:autoLink', ['source.com', 'destination.com']);
`

If users configure the Drupal GA module they confifure the same and the Drupal module creates the array of domains for them.

If I do not provide a list of domains to your script, how should it know what domain is in the cross domain list or not? Maybe you'd like to take a look into http://cgit.drupalcode.org/google_analytics/tree/js/google_analytics.js#n60 to get a better idea where I'm comming from. If a link points to a cross domain it *must not* track the click as an outbound click. If the link points to external and not my cross domains it can be logged as "Outbound links".

Where are you checking these autoLink array and conditionally track "Outbound clicks" or "nothing" if it is a cross domain link?

**Comment by philipwalton** [comment]
Plugins in analytics.js do not have access to each other, so I can't see what values a user has configured on that plugin. Also someone could require the `linker` plugin after the `outboundLinkTracker` plugin, so either way you'd have to set the configuration on both.

I don't see why this is a problem for Drupal. Couldn't you configure the `outboundLinkTracker`'s `shouldTrackOutboundLink` function with the same data captured from the GA module?

Would you prefer an option to specify a list of "local" domains, similar to the option in the `linker:autoLink` method?
