### ISSUE TITLE
Autotrack internal URL's that are redirects to external sites?

### ISSUE THREAD

**Issue by oscarfroberg** [googleanalytics/autotrack#68]
Let's say I have the following URL structure:

www.example.com/goto/site1
www.example.com/goto/site2
www.example.com/goto/site3

Is there a way to setup autotrack to track all these links, for example by matching www.example.com/goto/* ?

A workaround would of course be to setup a subdomain so that the links would look like:

ext.example.com/goto/site1
ext.example.com/goto/site2
ext.example.com/goto/site3

This way, if I'm understanding the documentation correctly, the links should be autotracked. But I'd rather not complicate things like this if there's an easier way.

**Comment by 1987yama3** [comment]
@oscarfroberg 
In v1.0, We could change linkSelector of "OutboundLinkTracker" by opts parameter.

In your case, please try the following code.

```js
ga('require', 'outboundLinkTracker', {
  linkSelector: 'a[href*="www.example.com/goto/"]'
});
```

**Comment by philipwalton** [comment]
Yes, you can use the [`shouldTrackOutboundLink`](https://github.com/googleanalytics/autotrack#shouldtrackoutboundlink) configuration option, which tells the plugin what to consider an outbound link.

The following configuration would extend the current outbound link tracking logic to *also* track any link whose `href` property contains the string `'www.example.com/goto/'`:

```js
ga('require', 'outboundLinkTracker', {
  shouldTrackOutboundLink: function(link) {
    return (link.hostname != location.hostname &&
        link.protocol.indexOf('http') === 0) ||
        link.href.indexOf('www.example.com/goto/') >= 0;
  }
});
```
