### ISSUE TITLE
Where to check the "socialTracker" report?

### ISSUE THREAD

**Issue by BanshaTang** [googleanalytics/autotrack#7]
I installed Autotrack, now I can see session duration, outbound links reports clearly.

But where can I check the "socialTracker" report? I read the usage guide time after time, and can't find this report in my GA's profile.

**Comment by philipwalton** [comment]
To view this data you can create a [custom report](https://support.google.com/analytics/answer/1151300?hl=en) with the metric [`ga:socialInteractions`](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=social_interactions&jump=ga_socialinteractions) and the dimensions [`ga:socialInteractionNetwork`](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=social_interactions&jump=ga_socialinteractionnetwork), [`ga:socialInteractionAction`](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=social_interactions&jump=ga_socialinteractionaction), and [`ga:socialInteractionTarget`](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=social_interactions&jump=ga_socialinteractiontarget).

Here's an [example query](https://ga-dev-tools.appspot.com/query-explorer/?start-date=7daysAgo&end-date=yesterday&metrics=ga%3AsocialInteractions&dimensions=ga%3AsocialInteractionNetwork%2Cga%3AsocialInteractionAction%2Cga%3AsocialInteractionTarget&sort=-ga%3AsocialInteractions) using the Query Explorer that reports on these dimensions/metrics.
