### ISSUE TITLE
Adding click source to Outbound Link

### ISSUE THREAD

**Issue by oscarfroberg** [googleanalytics/autotrack#72]
I just successfully added autotrack to my site (thanks to the help in #68!) but it doesn't seem like the page source gets recorded. I'm not 100% sure yet as I'm only able to see the realtime data, but I assume it's not. This small piece of information would be more or less crucial.

In outbound-link-tracker.js there's the following code:

`this.tracker.send('event', 'Outbound Link', 'click', link.href, {
      transport: 'beacon'
    });`

What I'm looking for is to change it to something like this:

`this.tracker.send('event', 'Outbound Link', location.href, link.href, {
      transport: 'beacon'
    });`

Is this possible somehow?

**Comment by philipwalton** [comment]
You'll be able to do something like this in version 1.0 (which you can try out now on the [1.0-dev](https://github.com/googleanalytics/autotrack/tree/1.0-dev) branch).

However, if I'm understanding your use case correctly, I don't think you actually need to do this. The `location.href` value is already being sent in the hit through the [`location`](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#location) field and/or the [`page`](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#page) field, so you can get this value in your reports through the [`ga:hostname`](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=page_tracking&jump=ga_hostname) and [`ga:pagePath`](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=page_tracking&jump=ga_pagepath) dimensions.

There's no reason to pass the URL of the current page as the event action or label.

**Comment by oscarfroberg** [comment]
Thanks Philip, you're right, the referring page is indeed getting sent through. I just can't see it in the realtime data. Now however it's all there in Behavior -> Events -> Pages.
