### ISSUE TITLE
Hit-Level Custom Dimensions/Metrics

### ISSUE THREAD

**Issue by neilkrishnan** [googleanalytics/autotrack#76]
Is there a way to add custom metric/dimension data to events being sent through the event-tracker.js plugin?

**Comment by philipwalton** [comment]
There is, in the [version 1 beta](https://github.com/googleanalytics/autotrack/pull/67). Once v1 comes out, you'll be able to add/override any field for any hit. And for hits that originate from user interactions with a DOM element, you'll be able to use declarative attributes to set those overrides as well (for all plugins).

For example, in v1 you'd be able to set a custom dimension on an outbound link like so:

```html
<a href="https://example.com" ga-dimension-1="true">Click Me</a>
```
