### ISSUE TITLE
Repo not registered on Bower?

### ISSUE THREAD

**Issue by aarongray** [googleanalytics/autotrack#78]
I'm interested in including autotrack in my project using Bower, but I [don't see it listed in the bower registry](http://bower.io/search/?q=autotrack).

Is there a reason why its not registered as a bower package?

**Comment by philipwalton** [comment]
It's already possible to `bower install` from Github, so I don't see any reason to explicitly support bower in the repo itself. If someone else wants to add it to the bower registry, that's fine with me.

**Comment by aarongray** [comment]
👍
