### ISSUE TITLE
Tracking internal forms

### ISSUE THREAD

**Issue by robwent** [googleanalytics/autotrack#79]
I feel like I'm missing something obvious here, but there's no tracking of internal form submissions, only forms that submit to other websites?

I've used the options to track internal forms by removing the domain check

    shouldTrackOutboundForm: function(form) {
    var action = form.getAttribute('action');
    // Checks that the action is set and starts with "http" to exclude relative
    // paths, then checks that it does not contain the string "example.com".
    return action &&
        action.indexOf('http') === 0 ;
       // && action.indexOf('example.com') < 0; //we wnat to track internal forma as well
      }

Is this something that should happen by default?

I would have thought that adding events to internal forms would be one of the most important things to track.

**Comment by philipwalton** [comment]
What you've done is perfectly fine to do. As to whether or not it should be the default, that's an interesting question.

My original thinking was that internal forms submit to a page on your domain, presumably a page that will send a pageview, so you can report on that form's usage by checking pageview counts for the destination page.

I could see an argument, though, for wanting all that data in one report.

**Comment by philipwalton** [comment]
Also, FWIW, in v1, you'll be able to customize the event category and action fields, so your reports won't have to say "Outbound Form" if you're tracking local forms as well.

**Comment by robwent** [comment]
Good point.

The client had actually set up goals for some of the forms that land the user on a thankyou page, but there are number of others that submit by ajax, which are the ones they asked me to add events to.

As the site is still being developed by another company, I added the autotrack script via a plugin (wordpress) so I didn't interfere with their code.

I'm not totally sure it's working yet though. I can see outboundform events for the ones that go to the thankyou page, but not for the ajax forms.

**Comment by philipwalton** [comment]
> I'm not totally sure it's working yet though. I can see outboundform events for the ones that go to the thankyou page, but not for the ajax forms.

It's possible whatever code is submitting your forms via ajax is also cancelling the event after submitting the form, which means the autotrack code has no way of knowing that the submit happened. (Just a guess.)

In v1 I've updated the event handlers to run in the event capture phase rather than the bubble phase, so it should be more resilient to this kind of thing.

**Comment by robwent** [comment]
I'll have a check through analytics tomorrow to see if anything popped up and look through their form code.
I'll let you know if I find anything.

**Comment by philipwalton** [comment]
FWIW, you don't have to wait until tomorrow to see if it's working. There are several ways to look at exactly what's being sent from the browser:
https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging

**Comment by robwent** [comment]
Yeah I know, I was using the analytics chrome plugin and real-time earlier, it's just getting late here and I haven't eaten all day :)

**Comment by robwent** [comment]
I think the issue was that the whole form was being loaded into the page via ajax after a click on a link.
The url change wasn't being detected (# being added to the url) which I guess might be down to a return false after the content gets loaded.

In this case, I fond some other random event being triggered elsewhere on the form submission so used that instead.

Feel free to close this one.

**Comment by philipwalton** [comment]
Great, I'm glad you found a solution.
