### ISSUE TITLE
Viewport support

### ISSUE THREAD

**Issue by cemo** [googleanalytics/autotrack#8]
Please support viewport for impressions as well.

**Comment by philipwalton** [comment]
Can you please clarify what you're asking? Are you talking about impressions for ad views, specifically when they're scrolled into the viewport?

**Comment by cemo** [comment]
Exactly, it would be very useful.

**Comment by philipwalton** [comment]
Since the [1.0](https://github.com/googleanalytics/autotrack/releases/tag/1.0.0) release, this can now be accomplished via the [`impressionTracker`](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/impression-tracker.md) plugin.
