### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by ligne13** [googleanalytics/autotrack#81]
Hi, 
after I include autotrack.js in my project, I get the following error :

Uncaught ReferenceError: require is not defined (autotrack.js line 19)

any help appreciated !
thanks

**Comment by philipwalton** [comment]
It sounds like you're not including the right autotrack file. Make sure you're including the [autotrack.js](https://github.com/googleanalytics/autotrack/blob/master/autotrack.js) file in the root directory of the repo.

**Comment by philipwalton** [comment]
Closing for reasons explained in #83.
