### ISSUE TITLE
No counting

### ISSUE THREAD

**Issue by Klarmann1988** [googleanalytics/autotrack#82]
Hi,

on one of my websites it´s working perfectly. But on deine-angelwelt.de are some issues.

When I insert this:

  ga('create', 'UA-???????-1', 'auto');
ga('require', 'autotrack');
  ga('send', 'pageview');

Its counting nothing - also no visitors. When I change this:

ga('create', 'UA-???????-1', 'auto');
  ga('send', 'pageview');
ga('require', 'autotrack');

It´s counting only the visitors, but no clicks.

Maybe there are some security plugins, which stop the .js?!

Best,
Paul

**Comment by philipwalton** [comment]
I went to [deine-angelwelt.de](http://deine-angelwelt.de) and it appears to be working for me.
