### ISSUE TITLE
Is this ready for primetime?

### ISSUE THREAD

**Issue by grantkemp** [googleanalytics/autotrack#86]
Is this library stable enough to be used on a large-ish publishing site in production? Would be useful to test it - but I don't want to have any potential issues with causing errors in our tracking. We currently use Tag manager for most interactions

**Comment by philipwalton** [comment]
The [1.0 release](https://github.com/googleanalytics/autotrack/pull/67) is going to happen very soon, so if you want to minimize your work, you may as well wait for that to happen.

That being said, yes, it is stable. Autotrack is being used by several sites that send more than a million hits per day, and I personally use it in production on several websites I maintain.
