### ISSUE TITLE
Translations need to be updated

### ISSUE THREAD

**Issue by philipwalton** [googleanalytics/autotrack#87]
@nebosuker and @stevezhuang, please update your forks at your convenience with the new documentation changes for the 1.0 release.

Also, please update the settings in your forks to allow for issues to be reported, so users can file issues with your forks rather than this repo. These instructions will show you how:
http://programmers.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork

Thanks, and let me know if you have any questions.

**Comment by stevezhuang** [comment]
Thank you @philipwalton for letting me know about the updates. I have already updated the setting that to turn the issue on via your reference. 
So basically, seems that new docs you mentioned that is from https://github.com/googleanalytics/autotrack/tree/master/docs, we should focus on all of translation for those files, am I correct? 

Thanks,
Steve.

**Comment by philipwalton** [comment]
@stevezhuang yes that's correct. It's the `README.md` in the main directory and then everything under `/docs/`.

**Comment by stevezhuang** [comment]
@philipwalton  Thanks for feedbacks. I think I have completed the translation for a couple of doc files. Such as the main README.md, common-options.md, upgrading.md. For those under doc folder, Definitely I will translate them on my daily basis once I am free up.  :)

**Comment by nebosuker** [comment]
Thank you Philip for letting me know.

Wow. /docs are huge, but I'll find my time to translate them.

And, congraturations on 1.0 release!


2016-07-20 7:43 GMT+09:00 Philip Walton <notifications@github.com>:

**Comment by philipwalton** [comment]
Thanks, @nebosuker. I very much appreciate it!

**Comment by philipwalton** [comment]
Since all translated repos have issues turned on, I'll close this. In the future, people can file translation issues against their respective repo.
