### ISSUE TITLE
Tracking right clicks not working

### ISSUE THREAD

**Issue by chrisdavenport** [googleanalytics/autotrack#94]
I tried to track both left and right click events on an A link with

`ga-on="mouseup"`

using

`ga('require', 'eventTracker', {events: ['click', 'mouseup']});

but only left-click events are visible in the Real Time view.  Am I missing something?  It looks like it should work, but apparently it doesn't.

**Comment by philipwalton** [comment]
I don't think right clicks generate a `mouseup` event in all browsers (I think only in Firefox). You might want to try [`contextmenu`](https://developer.mozilla.org/en-US/docs/Web/Events/contextmenu).
