### ISSUE TITLE
Tracking links for event tracker

### ISSUE THREAD

**Issue by ilarumk** [googleanalytics/autotrack#95]
I am not sure if this is the right place to ask. 
Currently I am using eventTracker to track the links on a div container, So I have setup data attributes on the div container and want to track the link clicks. 

Can i have the Event Label value as the value of href, 

This way, I can track the module category and which link was clicked?

**Comment by philipwalton** [comment]
This is possible, but you'll have to add a bit of code to make it work.

What you want to look at is the [`hitFilter`](https://github.com/googleanalytics/autotrack/blob/master/docs/common-options.md#hitfilter) option, which allows you to programmatically modify any hit prior to it being sent, and in the case of hits that are the result of user interaction with a DOM element, that element gets passed to the function as well.

Here's a basic example of how you could do what you're asking (note: you might have to modify it to work with your setup):

```js
ga('require', 'eventTracker', {
  hitFilter: function(model, element) {
    // Only sets the event label as the link `href` for clicks on elements
    // with an `href` property.
    if (element.href) {
      // Make sure to set the third parameter to `true` so this value only
      // gets sent with the current hit.
      // https://developers.google.com/analytics/devguides/collection/analyticsjs/model-object-reference#set
      model.set('eventLabel', element.href, true);  
    }
  }
});
```

**Comment by ilarumk** [comment]
One issue I am seeing is 
when I console.log, element in hitFilter, I get
<div class="xyz" data-on="click" data-event-category="blog" data-event-action="click">...</div>

It doesn't return all the links under the div or unable to find which link is actually clicked. 

Options for me are 
Add all the link in above div into event listeners and check if link is clicked and add use that in hitFilter. 

I am doing this on different div's 
eg. is
`
<div class="xyz" data-on="click" data-event-category="blog" data-event-action="click">
    <div class="col-md-12">
        <h3 class="text-primary today BlogListHeader">Blog & News</h3>
    </div>
    <div class="BlogList">
			<div class="col-md-12">
    <div class="row">
	<div class="blogitem">
	    <div class="col-xs-4 col-md-5">
		<a href="http://test.com.au/"><img class="img-responsive" src="seating_74ced3b40ec351b7700e96378f870fa1_w320_r1.6.jpg" alt="" /></a>
	    </div>
	    <div class="col-xs-8 col-md-7 no-pd-lft">
		<div class="headline">
		    <b><a href="http://test.com.au/">A Look Inside</a></b>
		</div>
				<div class="description">What you can expect from the renowned Airlines</div>
			    </div>
</div>
</div>
`

**Comment by philipwalton** [comment]
The `element` variable isn't going to reference the links within the div because you put the `data-*` attributes on the div itself. The `eventTracker` plugin isn't specific to links, it can be used with any type of element.
