### ISSUE TITLE
Ability to filter URLs

### ISSUE THREAD

**Issue by idris** [googleanalytics/autotrack#96]
It would be nice to be able to filter URLs, for example to strip out IDs from a URL.  Maybe this would be part of the `cleanUrlTracker`?

For me, I'd be using a filter like this:

```
function (url) {
  url.replace(/\/\d+/g, '/_id_');
}
```

**Comment by philipwalton** [comment]
Agreed.

Originally the `cleanUrlTracker` plugin included a `hitFilter` option, but since it doesn't send hits itself (just modifies hits sent by other code), that option was removed.

I'll make a note to add this capability in an upcoming release.

**Comment by philipwalton** [comment]
Closed via #131.
