### ISSUE TITLE
Reducing HTTP requests

### ISSUE THREAD

**Issue by vilav** [googleanalytics/autotrack#98]
Hello, 

In terms of implementation, assuming you use all the 9 plugins, that'd be 9 additional http requests. Is there  a way to reduce this and have 1-2 consolidated JS files (analytics.js + all_plugin.js) 

Thanks

**Comment by philipwalton** [comment]
I'm not sure if you intended to close this issue. Regardless, autotrack doesn't require an HTTP request per plugin. All the plugins are bundled into a single file, and optionally you can create a custom build with just the plugins you want.
