### ISSUE TITLE
Compatibility with Turbolinks

### ISSUE THREAD

**Issue by Startouf** [googleanalytics/autotrack#99]
Does your script work with Turbolinks ?

I found no mention of this on the readme. I know I had to adapt the original GA script to work with turbolinks 5, otherwise the tracking wouldn't take place during ajax-turbolinks navigation.

**Comment by philipwalton** [comment]
I can't mention every possible technology compatibility in the README, but I see no reason it wouldn't work with rails and turbolinks. I've also not heard any reports of it *not* working with turbolinks.

I'd recommend trying it out locally and if it doesn't work as you'd expect, definitely file a bug.

**Comment by yskkin** [comment]
For me, page view tracking works with turbolinks, but eventTracker is not.
Does eventTracker ignores nodes added after plugin instantiation?

**Comment by philipwalton** [comment]
> Does eventTracker ignores nodes added after plugin instantiation?

It does not. If you're using Rails, it actually sounds like this could be related to jquery-ujs stopping event propagation. I wrote about how this is an anti-pattern a few years ago:
https://css-tricks.com/dangers-stopping-event-propagation/

**Comment by yskkin** [comment]
I was so stupid that I forgot `ga-on` attribute 😝 
Fixing `ga-on` solved my problem.
And yes, provided link is very helpful. Thank you.
